### ISSUE TITLE
Update Docker Image for UISP 2.4.93

### ISSUE THREAD

**Issue by 4pack** [Nico640/docker-unms#104]
UISP 2.4.93 has been released. Can someone update the Docker image for this?

I can also do it as well, just won't be able to fully test it myself.

https://community.ui.com/releases/UISP-Application-2-4-93/24b6bb3b-a22e-4bf5-b739-8dec3cccf3da

**Comment by itrack** [comment]
<img width="529" alt="Screenshot 2024-05-04 at 12 18 39" src="https://github.com/Nico640/docker-unms/assets/2368391/9be300fe-a905-4c85-a08a-f814614b8529">

is already updated, try with:
docker pull nico640/docker-unms:latest
