### ISSUE TITLE
Update to 2.4.153

### ISSUE THREAD

**Issue by timwelchnz** [Nico640/docker-unms#108]
Due to the discontinuation of the cloud UISP free tier I've just installed this container, but I can't restore to it as it is older than the latest backup version.

Any chance of getting the image updated to 2.4.153?
[https://community.ui.com/releases/UISP-Application-2-4-153/b4be8ae1-2696-490a-b65d-f78a77433632](https://community.ui.com/releases/UISP-Application-2-4-153/b4be8ae1-2696-490a-b65d-f78a77433632)

 Cheers, Tim

**Comment by timwelchnz** [comment]
I note that this is underway as a workflow...
https://github.com/Nico640/docker-unms/actions/runs/11373606076

**Comment by Nico640** [comment]
Yep, missed the last version, thanks for the heads up!
