### ISSUE TITLE
Starting fresh (same Raspberry Pi, newer OS), sadly no results with 2.4.155.

### ISSUE THREAD

**Issue by GuruSR** [Nico640/docker-unms#109]
First off, I moved the config that was there out, totally, so the config was a brand new folder with nothing in it.

I never got the intro to start setting it up, most likely due to the below, the log was non-stop spammed, why it fails.

/config/unms/logs/ucrm.log
This repeats:
```
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
```

**Comment by Nico640** [comment]
Raspberry Pi 4B, right? Are you running Raspbian or something else? What's the OS (32 or 64bit?) / Docker version? Sounds like a permission issue, what command do you use to start / create the container?

**Comment by GuruSR** [comment]
Went from Buster to Bullfrog, 64 bit.  The command used to create the container is the same one I've used that worked before, it is trying to startup, created all the folders and such.  Docker 1.5-2, Docker-ce 5.19.03.15~30.

The script I use to run it.
```
docker stop unms_unms_1
docker rm unms_unms_1
docker run -d --name unms_unms_1 -p 8280:8280 -p 443:443 -p 2055:2055/udp -v /home/pi/unms/config:/config -e TZ=America/New_York -e HTTP_PORT=8280 nico640/docker-unms:latest
```

**Comment by Nico640** [comment]
Bullfrog? I assume you mean Bullseye?  `Docker 1.5-2`  is most likely a completely different package and has nothing to do with the `docker` command. `Docker-ce 5.19.03.15~30` sounds like a very old version of Docker, are you sure that's the installed version? Does `docker -v` also show `19.03.15`? If so, how did you install Docker? The correct way to install the newest Docker version would be to follow these docs: https://docs.docker.com/engine/install/debian/

**Comment by GuruSR** [comment]
Yes, sorry, Bullseye.  I opened Synaptic to list the docker versions.  Docker -v gives:  Docker version 19.03.15, build 99e3ed8919.

Docker was updated based on going to Bullseye from Buster, I saw it being updated.

**Comment by GuruSR** [comment]
RangeError: Model is only valid from Tue Dec 10 2019 to Tue Dec 10 2024

I'll have to see if the version is newer than what I have (says latest), but that was over a week ago.

**Comment by GuruSR** [comment]
Seems I updated at the wrong time!  This time around it did come up, so I'm re-setting it up because it is well over a year old and the data there isn't worth anything.

I didn't check, but is the expiration of the current one listed in the repo, if not, can you find it and add it?

**Comment by GuruSR** [comment]
Seems to have been the same as [\#110](https://github.com/Nico640/docker-unms/issues/110) and works.
