### ISSUE TITLE
Update current version

### ISSUE THREAD

**Issue by Roberto6969** [Nico640/docker-unms#12]
Hello and thank you for great job you are doing!

I have problem with updating current version through web interface. This problem existed with older versions as well.
If i try to update from initial message "New UNMS version available" or from "Update available" button in upper status line, after some time i get the message "The system update failed. Update timed out." every time. But in the same time i can update via system command line (docker-compose pull unms and docker-compose up -d).

**Comment by pr3mi3r3** [comment]
Update is only possible via docker image update. It is not possible over the webinterface.

**Comment by Roberto6969** [comment]
Great, thank you! Wouldn't it be fine if there will be warning against updating over the webinterface?

**Comment by Nico640** [comment]
Hi,

As pr3mi3r3 already mentioned, update only works by updating the image.
However, pressing the update button in UNMS shouldn't cause any problems, it just doesn't work.

Also, it is mentioned in the readme under limitations.

> In-app upgrades will not work. You can upgrade UNMS by downloading the latest version of this image.

**Comment by Roberto6969** [comment]
Thank You - I will keep this in mind. Do you have any intention to put in work this button in the future?

**Comment by Nico640** [comment]
Hi,

Currently not, as this would involve changing the actual UNMS code.
