### ISSUE TITLE
Can't add Super User

### ISSUE THREAD

**Issue by maritimelaw** [Nico640/docker-unms#13]
I upgraded from 0.13.3 to 1.0.6 and my only user was not a super user. I cannot find a way to run the command to create the super user. There is no unms-cli in this package
`sudo ~unms/app/unms-cli set-superadmin --username USERNAME `

**Comment by Nico640** [comment]
Hi,
To set a user as superadmin, you can launch a bash shell on the container, navigate to /home/app/unms and execute "node setpwd.js superadmin USER" to set a user as superadmin.

**Comment by Nico640** [comment]
I consider this matter closed, reopen if there's still issues with this.

**Comment by maritimelaw** [comment]
Oh, yeah I forgot to reply. Your fix worked perfectly

**Comment by philipp65** [comment]
inside the container (`docker exec -it unms bash`)
```
cd /home/app/unms/cli
node user.js superadmin USER
```
