### ISSUE TITLE
Crm bad gateway

### ISSUE THREAD

**Issue by MMan1982** [Nico640/docker-unms#14]
Hi,

I upgraded to 1.06, first of all: all of our devices(176) went to disconnected with wrong key error message, and crm won't start, saying bad gateway.

**Comment by Nico640** [comment]
Hi,

On which architecture are you running?

**Comment by MMan1982** [comment]
Hi, Sorry for that, it's a raspberry pi 3b, soon we will change to raspberry 4

**Comment by Nico640** [comment]
Hi,
I was able to reproduce the issue with crm, however, restarting the container fixed it.
Did you try restarting the container yet?

**Comment by MMan1982** [comment]
Hi,

I rebooted the raspberry,and tried docker stop and docker start container. Is it equal a restart i think but please say if i am wrong.

**Comment by Nico640** [comment]
Yeah it should be the same.
I just pushed a new build (UNMS 1.0.7) where I wasn't able to reproduce the bad gateway issue anymore.
If you still have the bad gateway issue with the latest build, then please attach the last few lines of the ucrm.log (/config/unms/logs/ucrm.log)

**Comment by MMan1982** [comment]
Thanks,update to 1.07 solved!Keep it up,good work,big thanks!!
