### ISSUE TITLE
UNMS not failing to create device backup

### ISSUE THREAD

**Issue by Trunkzeh** [Nico640/docker-unms#15]
I've got two devices on my UNMS install; both have been backing up correctly. However one now no longer backs up (last backup around September) - I've attempted a manual backup and this fails. Running UNMS 1.0.5 on x86-64 hardware (unRAID box on Intel E3-Xeon)

**Comment by Trunkzeh** [comment]
This came up on the logs:

{"name":"UNMS","hostname":"eede6c7cf5db","pid":4152,"component":"ws","cid":516,"mac":"18:e8:29:2b:56:fb","level":40,"error":"RPC request error: 39baead3-275c-4e35-9a24-bc4091d4caea backupConfig (110022) backupConfig: unable to read backup file","msg":"Backup for device 7baa4911-f65b-4112-88f6-d0f93aaaa7d2 failed","time":"2019-10-18T12:56:27.166Z","v":0}

**Comment by Nico640** [comment]
Hi,

I'm not sure what backup file UNMS is trying to read when creating a backup.
You can take a look inside the /config/unms/config-backups folder and check if all folders have the same permissions. 
Also, check the /config/unms/config-backups/7baa4911-f65b-4112-88f6-d0f93aaaa7d2/ folder.
If everything looks normal, you can try to rename the 7baa4911-f65b-4112-88f6-d0f93aaaa7d2 folder and try to create a backup again.

**Comment by Trunkzeh** [comment]
@Nico640 I've just checked and there does not exist a 7baa* folder inside ~/config-backups/; running permission scripts now on unRAID and will retry the backup attempt.

**Comment by Nico640** [comment]
Hi, can you check whether you're able to manually back up the config by logging onto the device?

**Comment by Trunkzeh** [comment]
Hey; I manually pulled a backup this morning (rather sizeable around 13mb)
just fine.

**Comment by Nico640** [comment]
Hmm, my EdgePoint R6 (same architecture) is running on 2.0.6 and it's backups are only 2kb in size, however, it's only running in switch mode at the moment. This could be an problem with the websocket connection between UNMS and the device, which would explain why it works on the webGUI. I assume you already tried restarting both UNMS and the ERX-SFP?

**Comment by Trunkzeh** [comment]
Yup; I believe the backup also backs up /config/ and it’s subdirs- mine is
fairly large as there are several .deb packages that are installed on first
boot; I can confirm this by unpacking the backup when I get home.

**Comment by Nico640** [comment]
I just confirmed that the issue is indeed the file size. I downloaded a 10mb dummy file onto the EdgePoint and the UNMS backup now fails, while I can still download it when directly accessing the device. I'll check if this also occurs with a normal UNMS install using the official install script.
The point at which it fails seems to be at around 5mb.

**Comment by Nico640** [comment]
Hi, I found out that this also happens on a regular UNMS install. I'm not sure if the ~5MB limit is by design or whether it's a bug.
I think the only way for you to fix this is to either delete unnecessary stuff on the device so that the backups are under 5MB, or open a thread on the Ubiquiti UNMS forum and ask whether this is normal, however, I'm not sure if they help you when you're running on a unofficial image like this.

**Comment by Trunkzeh** [comment]
Thanks @Nico640 I'll speak to the UNMS devs. Its definitely not an official
limit as I've checked the KB articles.

**Comment by Trunkzeh** [comment]
@Nico640 Just to keep things updated; I'm in contact with one of the unms developers UI-Radek with regards to the above issue - logs and configs have been submitted to him and he's looking into it. He has mentioned there is no 'limit' that UI have imposed on backups per-se. Will feedback :-)

**Comment by Trunkzeh** [comment]
Latest update from Ubiquiti; there is a limit of 5MB. This has now been accepted and filed on their internal bug tracker; the issue will be resolved in a firmware update to the edgemax suite as opposed to a change to UNMS I believe.

**Comment by Trunkzeh** [comment]
I've managed to get clean out some of the dpkg requirements in my config folder. Its now 3.1Mb and UNMS seems to be backing it up. They nonetheless have mentioned this will be resolved in a future edgemax firmware update.
