### ISSUE TITLE
Custom SSL certificates

### ISSUE THREAD

**Issue by JiriPodhorny** [Nico640/docker-unms#16]
Hallo,

i have problem with custom SSL certificates. 
I don't know, if it's related to your docker or UNMS (1.0.7) itself.
I had not this problem in UNMS 1.0.6 (afaik)

Content of my 'cert' folder is:

cert -> /config/cert
live.crt -> ./FQDN.crt
live.key -> ./FQDN.key
FQDN.crt
FQDN.key

where FQDN is full qualified domain name of my RasppberyPi.

UNMS startup fail with 'Oops ...' error, reload fails with Chrome warning about wrong SSL certificates.
When I look to 'cert' folder, both my certificates are replaced with newly generated self signed certificates.

I can workaround it by replacing these selfsigned certificates with my certificates, 
logging to container (docker-compose exec unms bash) 
and restarting www service (nginx -s reload)

Is it possible to avoid overwriting custom certificates?

Thanks

**Comment by Nico640** [comment]
Hi,
You can set the environment variables SSL_CERT and SSL_CERT_KEY to let UNMS handle your custom certs. So for example, SSL_CERT = FQDN.crt, SSL_CERT_KEY = FQDN.key. Your FQDN.crt and FQDN.key currently have to be in the /usercert/ directory, which you probably have to create. This isn't really convenient at the moment, because /usercert/ will reset when you update the container. I'll probably change this in the next build so that it uses /config/cert/ as the custom cert directory.

**Comment by JiriPodhorny** [comment]
Hallo,
thank you very much, it's working now 👍 

Just for summary:
- created folder usercert under volumes/unms
- certificates copied to both folders (volumes/unms/cert and /volumes/unms/usercert)
- docker-compose.yml modified -  SSL_CERT=FQDN.crt and SSL_CERT_KEY=FQDN.key added to environment section

Best Regards,
Jiri

**Comment by JiriPodhorny** [comment]
Complete description, how I get it work:

contents of docker-compose.yml
`version: '2'`
`services:`
`  unms:`
`    image: nico640/docker-unms:armhf`
`    restart: always`
`    ports:`
`      - 80:80`
`      - 443:443`
`      - 2055:2055/udp`
`    volumes:`
`      - ./volumes/unms:/config`
`    environment:`
`      - TZ=Europe/Prague`
`      - PUBLIC_HTTPS_PORT=443`
`      - PUBLIC_WS_PORT=443`
`      - SSL_CERT=raspi.crt`
`      - SSL_CERT_KEY=raspi.key`

files in ~/unms/volumes/unms/cert
` drwxr-xr-x 2 pi     pi   4096 říj 27 11:57 .`
` drwxr-xr-x 8  911   911  4096 říj 21 08:59 ..`
` lrwxrwxrwx 1 pi     pi         12 říj 20 20:01 cert -> /config/cert`
` -rw-r--r-- 1 pi     pi     1505 říj 26 22:34 custom.crt`
` -rw------- 1 pi     pi     1704 říj 26 22:34 custom.key`
` lrwxrwxrwx 1 root root     12 říj 27 11:57 live.crt -> ./custom.crt`
` lrwxrwxrwx 1 root root     12 říj 27 11:57 live.key -> ./custom.key`

files in ~/unms/volumes/unms/usercert 
` drwxr-xr-x 2 pi   root 4096 říj 27 11:34 .`
` drwxr-xr-x 8  911  911 4096 říj 21 08:59 ..`
` -rw-r--r-- 1 pi   pi   1505 říj 27 11:34 raspi.crt`
` -rw-r--r-- 1 pi   pi   1704 říj 27 11:34 raspi.key`
` lrwxrwxrwx 1 root root   16 říj 26 17:18 usercert -> /config/usercert`

Files custom.crt/.key in /cert are copy of raspi.crt/.key, they are used during start of UNMS

After start (docker-compose up -d) UNMS tries find certificates in /usercert
This folder is not available, so it keeps using certificate in /cert
You will get following info:

In Dashboard-Notifications:
> SSL certificate renewal failed. 
> Please check Settings/UNMS and the nginx.*.log file for error messages.

On Settings-UNMS-SSL Certificate page
> Last refresh of SSL certificate had failed.
> Timestamp: Today at 11:42
> Error: /bin/cat: /usercert/raspi.key: No such file or directory 
> Failed to create temp key from '/usercert/raspi.key'. 
> Keeping existing certificate for 'jxxx@pxxx.xxx'. 

Most important is, that it keeps using custom certificate and not generate self-signed stuff.

UNMS is then trying refresh certificate everyday (in my case at 5:00 AM) with repeating error notifications.

To get of rid these errors I did following:

` docker-compose exec unms bash`
` cd /`
` ln -s /config/usercert /usercert`
` exit`

Then in UMNS on Settings-UNMS-SSL Certificate press button 'Refresh Certificate'.

Since then everything works OK.

If you can add symbolic link /usercert -> /config/usercert in next revision, it will be perfect.

Best Regards
Jiri

**Comment by Nico640** [comment]
Link added in latest build (1.0.8)

**Comment by JiriPodhorny** [comment]
Just updated to 1.0.8 and it works as expected. Thank you.
