### ISSUE TITLE
DNS requests to UNMS's own FQDN

### ISSUE THREAD

**Issue by patricegautier** [Nico640/docker-unms#17]
Small thing I noticed..  I see a DNS request from the UNMS controller for its own FQDN every 15s.  

Any thoughts as to why?  That entry has a 1800s TTL.

**Comment by Nico640** [comment]
Hi,
I see what you mean. I just checked and it seems like an normal UNMS install also does this.
No idea why they do that though.

**Comment by Nico640** [comment]
I'm closing this as this doesn't seem to be an issue with this image itself.
Reopen if you don't think so.
