### ISSUE TITLE
Support package doesn't generate (1.0.9)

### ISSUE THREAD

**Issue by zenjabba** [Nico640/docker-unms#18]
I thought I would let you know that when asked by support to download the support package, it comes back with the error below. 

<img width="431" alt="Screen Shot 2019-12-11 at 5 00 25 PM" src="https://user-images.githubusercontent.com/679864/70840711-204db780-1de2-11ea-85ac-ea9786bc06fd.png">

**Comment by Nico640** [comment]
Hi,

As far as I know, that actually never worked, not even on the old 0.13.3 image.
It does however seem to work on the new 1.1.1 image, but the package only includes the latest UNMS and UCRM log file and no other logs like nginx, rabbitmq, etc. So I don't know how useful it'll be for support.

**Comment by Nico640** [comment]
Closed due to inactivity, reopen if there's still issues with this.
