### ISSUE TITLE
Autostart and how to disable autostart of unms

### ISSUE THREAD

**Issue by Roberto6969** [Nico640/docker-unms#19]
Maybe it is a stupid question but I can't disable autostart of unms.

How to enable/disable autostart of unms? 

Thank You for such a great job!

**Comment by Nico640** [comment]
Hi,
How did you create the container? using the docker run command or docker-compose?

**Comment by Roberto6969** [comment]
I have followed instructions on https://github.com/oznu/docker-unms/wiki/UNMS-on-Raspberry-Pi#updating-unms. It says to start with "docker-compose up -d".
But if i rename docker-compose.yml it still restarts on the same way. The only way to stop container after autostart is with "docker container stop name_of_cont".

**Comment by Nico640** [comment]
Hi,
Try this: docker update --restart=no name_of_cont

**Comment by Roberto6969** [comment]
Perfect - it works fine!

But now the other half of problem ... I have moved image from old Raspberry (docker save) to new one (docker load).
After start for the first time with "docker run -d --name unms -p 80:80 -p 443:443 -p 2055:2055/udp -v /volumes/unms:/config nico640/docker-unms:armhf" it starts automatically.
So far so good. But then i upgraded to version 1.1.2 (docker-compose pull unms, docker-compose up -d). Now new version starts automatically but without any data - clean installation. In the container with old version i still have whole configuration.

The question is how can i move data (devices, sites, settings, ...) from old version to a new one?
Is it better way to upgrade and to keep all the data?

**Comment by Nico640** [comment]
Hi,
The actual data is not kept in the container itself, it's in the /config directory which is mounted on the container, which seems to be "/volumes/unms" in your case. Could it be that your old container has a different folder mounted than the new one, or you didn't move that folder from the old Raspberry to the new one?

**Comment by Roberto6969** [comment]
True - old container has a different folder than new one.
From _docker container inspect_:
**New one:**
"HostConfig": {
            "Binds": [
                "/home/pi/IOTstack/services/unms/volumes/unms/unms:/config:rw"
            ],

**Old one:**
"HostConfig": {
            "Binds": [
                "/volumes/unms:/config"
            ],

I have both containers on new Raspberry and I can run either old one or new one. In case i run old one i have all the data and config.
What is the best solution to transfer data and config to new one? I don't need to keep new path of unms - i mean i can move unms to same locations as old one has it.

**Comment by Nico640** [comment]
Hi,
I would try changing the path of the config folder from the new to the old one. So in your case, change "/home/pi/IOTstack/services/unms/volumes/unms/unms:/config:rw" to "/volumes/unms:/config"

**Comment by Roberto6969** [comment]
Hi,
That was the point. If someone will fall in the same problem: the config file is a json file at the location ‘ /var/lib/docker/containers/container-id/config.v2.json ‘. It is not easy to access file’s location due to security but the easiest way to edit file is using mc. You have to change path in »HostConfig« and »Mounts« (at least I changed both).
I have managed to move whole unms directoy structure to new location, recreate container and keep all the settings and data from first configuration.

Anyway, I would like to know what content is in backup. I have tried to restore backup but I couldn't succeed to get, for example, sites to a new clean configuration.

**Comment by Nico640** [comment]
I assume you're talking about the UNMS backup. According to the [UNMS help page](https://help.ubnt.com/hc/en-us/articles/115015690027-UNMS-v1-How-to-Back-Up-UNMS), these backups only contain essential data, but the devices, sites, users, settings, etc. are definetly part of that data.
Not sure why it didn't work for you. Did you get any error messages?

**Comment by Roberto6969** [comment]
Yes, about UNMS backup. I didn't get any error messages. Backup finished well as always but restore did not restore any data (neither username), which should be included in backup. Could be this kind of errors seen somewhere in UNMS?

**Comment by Nico640** [comment]
Not sure, at least I haven't seen this kind of problem yet.
I just tested backup and restore with two seperate containers and it seems to work fine for me.

**Comment by zenjabba** [comment]
I also tested backup and restore and worked perfectly for me with 1.1.2

**Comment by Nico640** [comment]
Closed due to inactivity.
