### ISSUE TITLE
 ERROR:  relation "crm_db_version_view" does not exist at character 19

### ISSUE THREAD

**Issue by caffeineflo** [Nico640/docker-unms#20]
I haven't used UNMS after oznu deprecated the repo and so I did setup a fresh installation taken from the example docker-compose.yml

The only error output I'd be seeing on the container would be 

```
id: 'unms': no such user
Waiting for unms to create user...
Checking CRM database schema version.
ERROR:  relation "crm_db_version_view" does not exist at character 19
STATEMENT:  SELECT value FROM crm_db_version_view
relation "crm_db_version_view" does not exist
Retrying in 10s
```

Nothing else would come up on the container. 

Googling the issues leads me that migration wouldn't run properly, but executing it manually throws hostname resolution errors.

**Comment by Nico640** [comment]
Hi,
That usually means that the UCRM module isn't done with it's database migration yet.
Have a look into the UNMS and UCRM log files (/config/unms/logs/unms.log / ucrm.log), the UCRM log should have something like "Start database migration." in it.
The UCRM database migration can take quite a while when doing a fresh install. How long did you wait?

**Comment by Mubby** [comment]
I am also getting a similar error, have left the system for over an hour but it seems to keep looping on the same section, secondly no logs are being created in the log directory which I am assuming is related to the error that pops up in conjunction with the crm_db_version_view error, this is the part of the log that keeps repeating:
`/var/run/postgresql:5432 - accepting connections
1000
/usr/src/ucrm/scripts/init_log.sh
/usr/src/ucrm/scripts/dirs.sh
{"message":"Creating directories.","channel":"dirs.sh","datetime":"2020-01-25T15:37:49+13:00","severity":"INFO","level":200}
{"message":"Done creating directories.","channel":"dirs.sh","datetime":"2020-01-25T15:37:50+13:00","severity":"INFO","level":200}
{"message":"Creating symbolic links.","channel":"dirs.sh","datetime":"2020-01-25T15:37:50+13:00","severity":"INFO","level":200}
{"message":"Creating symbolic link for /usr/src/ucrm/app/data.","channel":"dirs.sh","datetime":"2020-01-25T15:37:51+13:00","severity":"INFO","level":200}
{"message":"Creating symbolic link for /usr/src/ucrm/app/EmailQueue.","channel":"dirs.sh","datetime":"2020-01-25T15:37:52+13:00","severity":"INFO","level":200}
{"message":"Creating symbolic link for /usr/src/ucrm/app/logs.","channel":"dirs.sh","datetime":"2020-01-25T15:37:52+13:00","severity":"INFO","level":200}
{"message":"Creating symbolic link for /usr/src/ucrm/web/uploads.","channel":"dirs.sh","datetime":"2020-01-25T15:37:53+13:00","severity":"INFO","level":200}
{"message":"Creating symbolic links for /data/updates.","channel":"dirs.sh","datetime":"2020-01-25T15:37:53+13:00","severity":"INFO","level":200}
{"message":"Publishing current /usr/src/ucrm/app/config/version.yml.","channel":"dirs.sh","datetime":"2020-01-25T15:37:53+13:00","severity":"INFO","level":200}
{"message":"Done creating symbolic links.","channel":"dirs.sh","datetime":"2020-01-25T15:37:53+13:00","severity":"INFO","level":200}
/usr/src/ucrm/scripts/parameters.sh
{"message":"Replacing configuration parameters.","channel":"parameters.sh","datetime":"2020-01-25T15:37:54+13:00","severity":"INFO","level":200}
In Kernel.php line 765:

  Unable to create the logs directory (/usr/src/ucrm/app/logs)  


{"message":"Done replacing configuration parameters.","channel":"parameters.sh","datetime":"2020-01-25T15:37:54+13:00","severity":"INFO","level":200}
/usr/src/ucrm/scripts/cron_jobs_disable.sh
crontab /tmp/crontabs/server
/usr/src/ucrm/scripts/database_ready.sh
{"message":"Waiting for database.","channel":"database_ready.sh","datetime":"2020-01-25T15:37:55+13:00","severity":"INFO","level":200}
{"message":"Database ready.","channel":"database_ready.sh","datetime":"2020-01-25T15:37:55+13:00","severity":"INFO","level":200}
/usr/src/ucrm/scripts/database_create_extensions.sh
{"message":"Creating database extensions.","channel":"database_create_extensions.sh","datetime":"2020-01-25T15:37:55+13:00","severity":"INFO","level":200}
{"message":"Extension \"citext\" exists.","channel":"database_create_extensions.sh","datetime":"2020-01-25T15:37:57+13:00","severity":"INFO","level":200}
Checking CRM database schema version.
ERROR:  relation "crm_db_version_view" does not exist at character 19
STATEMENT:  SELECT value FROM crm_db_version_view
relation "crm_db_version_view" does not exist
Retrying in 10s
{"message":"Extension \"unaccent\" exists.","channel":"database_create_extensions.sh","datetime":"2020-01-25T15:37:58+13:00","severity":"INFO","level":200}
{"message":"Extension \"uuid-ossp\" exists.","channel":"database_create_extensions.sh","datetime":"2020-01-25T15:38:00+13:00","severity":"INFO","level":200}
{"message":"Finished creating database extensions.","channel":"database_create_extensions.sh","datetime":"2020-01-25T15:38:00+13:00","severity":"INFO","level":200}
/usr/src/ucrm/scripts/migrate.sh
{"message":"Start replace shared views.","channel":"migrate.sh","datetime":"2020-01-25T15:38:01+13:00","severity":"INFO","level":200}
In Kernel.php line 765:
  Unable to create the logs directory (/usr/src/ucrm/app/logs)  
Makefile:12: recipe for target 'server_with_migrate' failed
make: *** [server_with_migrate] Error 1
FATAL:  role "root" does not exist`

Should not this is trying to run on a raspberry pi 4, all other folders seem to create fine and get populated, have tried cleaning on the folder and starting again but just gets to the same place.

**Comment by Nico640** [comment]
Hi,
Seems like UNMS is waiting for "crm_db_version_view" to be created by UCRM, however, UCRM fails to start because it can't create the logs directory, which is a symbolic link to "/data/log/ucrm/app/logs".
Can you check if that symbolic link is created in the container?

**Comment by Mubby** [comment]
Yes it appears that it is created: logs -> /data/log/ucrm/app/logs

Inside the logs folder is just a prod.log file which is empty

**Comment by Mubby** [comment]
Just to follow up, deleting the symbolic link at the right point gets past the error and a new log directory is created (one that's not a symbolic link) and now all I am getting is:

```
Checking CRM database schema version.
No data returned from the query.
Retrying in 10s
```

So I am assuming it may be migrating properly now? Will let it run a let you know.

**Comment by Mubby** [comment]
So it has now started properly and seems to be working, though that error message about not being able to create the log directory has come back again.
```
In Kernel.php line 765:
  Unable to create the logs directory (/usr/src/ucrm/app/logs)  
```

**Comment by Nico640** [comment]
The empty prod.log file is actually normal.
Because it seems to work without the symbolic link, it could have something to do with the data -> /config/unms/ucrm link or the /config mapping. You can try removing the container & image and recreate it without the /config mapping.

**Comment by caffeineflo** [comment]
Sorry to come back to this discussion after such a long time. In fact, I did let the container run since we last talked and still experience the same issue. 

If you want me to try something to get the container going, please let me know! Happy to reply back with the results

**Comment by Nico640** [comment]
Hi, you can try to recreate the container, wipe the /config mapping and get a log of it's first startup.

**Comment by caffeineflo** [comment]
I hope I understood you correctly to remove the volume mapped to /config and recreate the container?!

If so, nothing has changed, the startup is still the same with the same error messages 

```
ERROR:  relation "crm_db_version_view" does not exist at character 19,
STATEMENT:  SELECT value FROM crm_db_version_view,
relation "crm_db_version_view" does not exist
```

**Comment by Nico640** [comment]
Strange. If you take a look in the container, there should normally be two log files at /config/unms/logs (unms.log / ucrm.log). If they exist, check them for any errors (especially the ucrm.log, as ucrm seems to be unable to start).
Also, what device / system are you running this on?

**Comment by Nico640** [comment]
Closed due to inactivity.

**Comment by EfficientSetting** [comment]
I know this issue is old and I haven't followed up in time (sorry @Nico640). 

I was getting another error that basically spammed `id: user unms not found` (so the UNMS user referenced in a few scripts never existed), so I created user unms with `groupadd unms; useradd -d /home/app/unms -g unms unms` and the migration went through and UNMS is running.

I wonder if the unms user needs any other permissions  or groups @Nico640 ?

**Comment by Nico640** [comment]
Not sure why the user wouldn't get created. The UCRM service (/etc/services.d/ucrm/run) waits until the unms user exists, therefore the spamming. The NGINX service executes /entrypoint.sh, which is supposed to create the unms user if it doesn't exist. 
If you want to test this or if it happens again, you could try to execute /entrypoint.sh manually and see if the user gets created.
I'm not sure under what circumstances this problem occurs as I haven't been able to reproduce this.

**Comment by EfficientSetting** [comment]
Finally got around testing this and I might found something that is an improvement here:

The user isn't created, because `adduser` errors out since UID 1000 is already taken for the abc user on the container (boot2docker on a Mac Mini running through parallels). So `adduser` says that UID 1000 is already taken.

I'm not sure if this is only a boot2docker standard, but I've seen this elsewhere, where my GID and UID are slightly off (UID 1000, GID 100). That's also how I setup the container, using docker-compose and setting PGID and PUID in the environmental variables for my docker user (as I do it for every container).
I did recreate the image from the dockerfile to give it a try, but that didn't work out for me either.
