### ISSUE TITLE
Postgres not initializing 

### ISSUE THREAD

**Issue by devros42** [Nico640/docker-unms#22]
I had this up and running fine, and then when I tried to access it last week it wasn't coming up properly.  I blew away the config directory, installed it again, but now when it starts up it does not seem to be creating the proper config files.

It creates these directories:

cert/  logs/  postgres/  redis/  unms@  usercert/

but, for example, the postgres dir is empty and when you look at the logs it's just the following in a loop:

-----------

Running entrypoint.sh
Will use existing SSL certificate
Entrypoint finished
Calling exec
postgres: could not access the server configuration file "/config/postgres/postgresql.conf": No such file or directory
2020/01/17 22:06:39 [emerg] 7699#7699: open() "/data/log/ucrm/nginx/suspended_service_access.log" failed (40: Too many levels of symbolic links)

nginx: [emerg] open() "/data/log/ucrm/nginx/suspended_service_access.log" failed (40: Too many levels of symbolic links)

/var/run/postgresql:5432 - no response
Waiting for postgres to come up...
/var/run/postgresql:5432 - no response
Waiting for postgres to come up...
Starting nginx...
Running entrypoint.sh
Starting postgres...
Will use existing SSL certificate
Entrypoint finished
Calling exec
postgres: could not access the server configuration file "/config/postgres/postgresql.conf": No such file or directory
2020/01/17 22:06:40 [emerg] 7716#7716: open() "/data/log/ucrm/nginx/suspended_service_access.log" failed (40: Too many levels of symbolic links)

nginx: [emerg] open() "/data/log/ucrm/nginx/suspended_service_access.log" failed (40: Too many levels of symbolic links)

---------------

Is there something obvious I'm missing?

**Comment by Nico640** [comment]
Hi,
Looks like you deleted the config directory without recreating the container, so it tries to start without doing the first-time container setup.
Try deleting the config directory again and recreating the container.

**Comment by devros42** [comment]
So, I'm running this on unraid.  I removed the container, had it delete the image, blew away the mapped config folder and then did a full reinstall with the defaults and get the following:

2020/01/22 04:25:41 [error] 806#806: *155 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.55.1, server: , request: "GET // HTTP/1.1", upstream: "http://127.0.0.1:8082//", host: "192.168.55.58"

Starting postgres...
postgres: could not access the server configuration file "/config/postgres/postgresql.conf": No such file or directory
/var/run/postgresql:5432 - no response
/var/run/postgresql:5432 - no response
Waiting for postgres to come up...
Waiting for postgres to come up...
Starting postgres...
postgres: could not access the server configuration file "/config/postgres/postgresql.conf": No such file or directory
/var/run/postgresql:5432 - no response
Waiting for postgres to come up...
/var/run/postgresql:5432 - no response
Waiting for postgres to come up...
Starting postgres...
postgres: could not access the server configuration file "/config/postgres/postgresql.conf": No such file or directory
/var/run/postgresql:5432 - no response
/var/run/postgresql:5432 - no response
Waiting for postgres to come up...
Waiting for postgres to come up...
Starting postgres...
postgres: could not access the server configuration file "/config/postgres/postgresql.conf": No such file or directory
/var/run/postgresql:5432 - no response
Waiting for postgres to come up...
/var/run/postgresql:5432 - no response

**Comment by Nico640** [comment]
Thats strange. I also have an instance running on unraid without any issues.
Since your postgres folder is empty, you can try manually initializing the DB by executing `s6-setuidgid postgres initdb --locale=C.UTF-8` in the container and see what it's outputting.

**Comment by devros42** [comment]
I'm on vacation until tomorrow and have what is basically dialup for bandwidth, but I did try launching that command within the container and got:

# docker exec -it unms /bin/bash
root@ba9d7b4f2668:/home/app/unms# s6-setuidgid postgres initdb --locale=C.UTF-8
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "C.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /config/postgres ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default timezone ... America/New_York
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... LOG:  could not link file "pg_xlog/xlogtemp.1240" to "pg_xlog/000000010000000000000001": Function not implemented
FATAL:  could not open file "pg_xlog/000000010000000000000001": No such file or directory
child process exited with exit code 1
initdb: removing contents of data directory "/config/postgres"

**Comment by Nico640** [comment]
Haven't seen that yet. Could be an issue with unraid like seen [here](https://github.com/sameersbn/docker-postgresql/issues/20).
You can try removing the /config mapping for the container and check if it's still failing.

**Comment by devros42** [comment]
Very strange.  I forced it to create the config folder directly on the cache and it worked just fine.  Strange thing is I had this all working fine with the old setup.  Didn't log in very often, so no sure exactly when it stopped working.  Thanks!
