### ISSUE TITLE
Unable to remove 2FA via cli

### ISSUE THREAD

**Issue by maritimelaw** [Nico640/docker-unms#23]
Hello, I'm trying to disable 2FA for a user. I'm having troubles finding how to run

`unms-cli disable-two-factor --username <username>`

on this container

**Comment by maritimelaw** [comment]
I found it
`cd /home/app/unms/cli`
`node user.js two-factor <username>`

**Comment by Nico640** [comment]
I'm glad you found it!
There's currently no unms-cli in this image, so everything has to be done with the commands that unms-cli uses internally.
