### ISSUE TITLE
Switch Firmwareupgrade fail

### ISSUE THREAD

**Issue by rauch89** [Nico640/docker-unms#24]
When upgrading switches through the unms webinterface i get the following error:

> xyz_switch upgrade from firmware version 1.8.2 to firmware version 1.9.0 has failed because of error (SSL_connect failed with error -313: revcd alert fatal error).

Tried with different switches.

Upgrading routers works flawlessly...

Deployment uses traefik reverse proxy

**Comment by Nico640** [comment]
Hi,
what system are you running unms on and which switches have this problem?
Sadly I do not have any unms capable switches to test this.
Does the log of the switch show any more information?

**Comment by Nico640** [comment]
Closed due to inactivity.
