### ISSUE TITLE
Sudo Lecture

### ISSUE THREAD

**Issue by JiriPodhorny** [Nico640/docker-unms#25]
Hello,

I found new problem with SSL certificate renewal:
Everyday certificate renewal procedure now fails, because it needs sudo.
Sudo is now configured to print Lecture info, so error message looks like:

`Last refresh of SSL certificate had failed.`
`Timestamp: Today at 6:00`
`Error: `
`We trust you have received the usual lecture from the local System `
`Administrator. It usually boils down to these three things: `
`#1) Respect the privacy of others.` 
`#2) Think before you type.` 
`#3) With great power comes great responsibility. `
`sudo: no tty present and no askpass program specified` 
`Failed to create temp key from '/usercert/***.key'.` 
`Keeping existing certificate for '***@***.***'. >`

It not break functionality of the UNMS as it keeps using existing user certificates.
It will break functionality, if somebody use Let's Encrypt cetrificates.

Most probably this can be solved by adding line

`Defaults  lecture="none"`

to /etc/sudoers

Best Regards
Jiri

**Comment by Nico640** [comment]
Hello,
Thanks for the report!
Did you test if adding this to the /etc/sudoers does indeed fix the problem?

**Comment by JiriPodhorny** [comment]
Hello,
I did not test it, I can't change /etc/sudoers file (when I tried to change it, it asks password, which I don't know).
I just guess, that it may help.
I also find, that you removed this line from /etc/sudoers:

`unms ALL=(ALL) NOPASSWD:SETENV: /copy-user-certs.sh reload` 

I also don't know, if this line is necessary

**Comment by Nico640** [comment]
Should be fixed in the latest build.
Please try it and see if it works now

**Comment by JiriPodhorny** [comment]
It's OK now.
Thank You.
