### ISSUE TITLE
Upgrade question 

### ISSUE THREAD

**Issue by Danabw** [Nico640/docker-unms#27]
Re:

"You can upgrade UNMS by downloading the latest version of this image."

Sorry, can I ask for a little Docker noob upgrade help? This is the first time I've had to upgrade a Docker install. I've been Googling around but don't find a consistent answer (maybe because there are multiple ways?) to upgrade to the new release. I'm a bit confused.

Is it as simple removing the current unms container and repeating the command below that I used the first time I installed?

sudo docker run -d --name unms -p 80:80 -p 443:443 -p 2055:2055/udp -v /var/lib/docker-config/unms:/config nico640/docker-unms:armhf

**Comment by Nico640** [comment]
Yes, you pull the new image, remove the current container and create a new one.
A update procedure could look like this (in your case):
```
sudo docker pull nico640/docker-unms:armhf
sudo docker stop unms
sudo docker rm unms
sudo docker run -d --name unms -p 80:80 -p 443:443 -p 2055:2055/udp -v /var/lib/docker-config/unms:/config nico640/docker-unms:armhf
```

**Comment by Danabw** [comment]
Thanks very much! Appreciate you taking the time to help me w/such basic stuff. Love your Docker UNMS, thanks very much for putting it together and keeping it up to date, it's made things so much simpler for me.

**Comment by Danabw** [comment]
Shoot - I've screwed something up, not sure how. Executed the command above via cut/paste, didn't get any errors, yet UNMS won't start. Reconfirmed that I have the right config directory, but UNMS fails to start. 

Oddly, when I look in the config directory it's empty: 

`pi@raspberrypi4:~ $ ls -ls docker-config/unms/config
total 0
`
From docker info I get: 
`pi@raspberrypi4:~ $ sudo docker info
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 1
  Paused: 0
  Stopped: 1
 Images: 3
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.97-v7l+
 Operating System: Raspbian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: armv7l
 CPUs: 4
 Total Memory: 1.894GiB
 Name: raspberrypi4
 ID: xxxxxxxxxxxxx
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
pi@raspberrypi4:~ `

Docker ps:
`pi@raspberrypi4:~ $ sudo docker ps
CONTAINER ID        IMAGE                       COMMAND             CREATED             STATUS              PORTS                                                              NAMES
096eefc5d7c4        nico640/docker-unms:armhf   "/init"             40 minutes ago      Up 23 minutes       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:2055->2055/udp   unms`

Web browser address I'm using is the same I was using before the upgrade: 

https://192.168.10.3/nms/devices

Sorry to bother again. Any suggestions?

**Comment by Nico640** [comment]
The unms folder actually looks fine. Take a look into /var/lib/docker-config/unms/unms/logs/unms.log and check if there's any obvious error shown.

**Comment by Danabw** [comment]
I'm clearly no expert on UNMS logs :-) but I do see this error recurring today: 

{"message":"UNMS did not start in time, restarting container.","channel":"web.sh","datetime":"2020-04-26T14:22:52+00:00","severity":"WARNING","level":300}
Makefile:12: recipe for target 'server_with_migrate' failed
make: *** [server_with_migrate] Error 1
/usr/src/ucrm/scripts/init_log.sh
/usr/src/ucrm/scripts/dirs.sh`

`(127.0.0.1:8081).","channel":"unms_ready.sh","datetime":"2020-04-26T14:22:29+00:00","severity":"INFO","level":200}
{"message":"Waiting for UNMS (127.0.0.1:8081).","channel":"unms_ready.sh","datetime":"2020-04-26T14:22:32+00:00","severity":"INFO","level":200}
{"message":"Waiting for UNMS (127.0.0.1:8081).","channel":"unms_ready.sh","datetime":"2020-04-26T14:22:35+00:00","severity":"INFO","level":200}
{"message":"Waiting for UNMS (127.0.0.1:8081).","channel":"unms_ready.sh","datetime":"2020-04-26T14:22:39+00:00","severity":"INFO","level":200}
{"message":"Waiting for UNMS (127.0.0.1:8081).","channel":"unms_ready.sh","datetime":"2020-04-26T14:22:42+00:00","severity":"INFO","level":200}
{"message":"Waiting for UNMS (127.0.0.1:8081).","channel":"unms_ready.sh","datetime":"2020-04-26T14:22:45+00:00","severity":"INFO","level":200}
{"message":"Waiting for UNMS (127.0.0.1:8081).","channel":"unms_ready.sh","datetime":"2020-04-26T14:22:48+00:00","severity":"INFO","level":200}
{"message":"Waiting for UNMS (127.0.0.1:8081).","channel":"unms_ready.sh","datetime":"2020-04-26T14:22:52+00:00","severity":"INFO","level":200}
{"message":"UNMS did not start in time, restarting container.","channel":"web.sh","datetime":"2020-04-26T14:22:52+00:00","severity":"WARNING","level":300}
Makefile:12: recipe for target 'server_with_migrate' failed
make: *** [server_with_migrate] Error 1
/usr/src/ucrm/scripts/init_log.sh
/usr/src/ucrm/scripts/dirs.sh`

**Comment by Nico640** [comment]
That looks like the UCRM log, which doesn't seem to be the issue as it's waiting for UNMS to start.
Did you check the unms.log for something similar? 
Could you paste the last few lines of the unms.log here?

**Comment by Danabw** [comment]
Oh man, clumsy copy/paste, sorry about that, I grabbed the wrong file. 
Here's a subset of the unms log, shows a consistent error that repeats, refers to it likely being an npm error. I could not get to the directory they refer to in the log below: 
 - /home/app/.npm/_logs/2020-04-26T14_20_14_770Z-debug.log
I don't see any "app" folder in my home directory. 

Thanks for any additional help. 
I'm going to run a general apt-get update on the pi to see if that helps at all. 

```
{"name":"UNMS","hostname":"096eefc5d7c4","pid":2201,"level":60,"err":{"message":"Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379","name":"Error","stack":"Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)","code":"ECONNREFUSED"},"msg":"Redis connection failed, terminating...","time":"2020-04-26T14:20:14.676Z","v":0}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! unms-server@1.1.7 start: `node --max_old_space_size=2048 index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the unms-server@1.1.7 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/app/.npm/_logs/2020-04-26T14_20_14_770Z-debug.log
Running docker-entrypoint npm start
Version: 1.1.7+713785de8.2020-04-22T14:24:35+02:00
Waiting for database containers
NOTICE:  extension "timescaledb" does not exist, skipping
DROP EXTENSION
LOADING Redis is loading the dataset in memory

Restoring backups and/or running migrations
yarn run v1.21.1
$ yarn backup:apply && yarn migrate && yarn check-crm-db
$ node ./cli/apply-backup.js
$ node ./cli/migrate.js
Extension 'uuid-ossp:1.1 installed.
Extension 'pgcrypto:1.3 installed.
Extension 'cube:1.2 installed.
Extension 'earthdistance:1.1 installed.
Extension 'unaccent:1.1 installed.
Setting database schema version to 1.1.7
Done
$ node cli/check-crm-db.js
Checking CRM database schema version.
CRM database schema version is '1.1.7'.
Done in 8.86s.
Exec npm start with memory limit 629

> unms-server@1.1.7 prestart /home/app/unms
> yarn backup:apply && yarn migrate && yarn check-crm-db

yarn run v1.21.1
$ node ./cli/apply-backup.js
Done in 2.74s.
yarn run v1.21.1
$ node ./cli/migrate.js
Extension 'uuid-ossp:1.1 installed.
Extension 'pgcrypto:1.3 installed.
Extension 'cube:1.2 installed.
Extension 'earthdistance:1.1 installed.
Extension 'unaccent:1.1 installed.
Setting database schema version to 1.1.7
Done
Done in 1.96s.
yarn run v1.21.1
$ node cli/check-crm-db.js
Checking CRM database schema version.
CRM database schema version is '1.1.7'.
Done in 1.99s.

> unms-server@1.1.7 start /home/app/unms
> node --max_old_space_size=2048 index.js

{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":30,"msg":"Master 3037 is running","time":"2020-04-26T14:20:37.859Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":30,"msg":"Connected to PostgreSQL server version: PostgreSQL 9.6.17 on armv7l-unknown-linux-gnueabihf, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 32-bit","time":"2020-04-26T14:20:40.944Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":30,"msg":"Registering plugins","time":"2020-04-26T14:20:41.688Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Registering plugin 'cache'...","time":"2020-04-26T14:20:48.773Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Plugin 'cache' registration done.","time":"2020-04-26T14:20:48.774Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Registering plugin 'dal'...","time":"2020-04-26T14:20:48.775Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Plugin 'dal' registration done.","time":"2020-04-26T14:20:48.858Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Registering plugin 'messageHub'...","time":"2020-04-26T14:20:48.860Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"component":"os","level":20,"totalmem":"1939MB","freemem":"107MB","loadavg":"2.185546875, 2.32177734375, 1.34765625","uptime":"566912s","msg":"","time":"2020-04-26T14:20:48.870Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"component":"proc","level":20,"delay":"11.19ms","cpu":"110.21%","memory":"143MB","uptime":"13s","msg":"[api]","time":"2020-04-26T14:20:48.880Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"component":"message-hub","level":30,"msg":"Starting RabbitMQ connection watchdog","time":"2020-04-26T14:20:48.958Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Plugin 'messageHub' registration done.","time":"2020-04-26T14:20:48.959Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Registering plugin 'notificationHub'...","time":"2020-04-26T14:20:48.960Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Plugin 'notificationHub' registration done.","time":"2020-04-26T14:20:49.055Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Registering plugin 'settings'...","time":"2020-04-26T14:20:49.057Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Plugin 'settings' registration done.","time":"2020-04-26T14:20:49.096Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Registering plugin 'reporting'...","time":"2020-04-26T14:20:49.098Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Plugin 'reporting' registration done.","time":"2020-04-26T14:20:49.112Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Registering plugin 'scheduler'...","time":"2020-04-26T14:20:49.114Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Plugin 'scheduler' registration done.","time":"2020-04-26T14:20:49.119Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Registering plugin 'auth'...","time":"2020-04-26T14:20:49.120Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":30,"msg":"Deleted transient tokens.","time":"2020-04-26T14:20:49.133Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Plugin 'auth' registration done.","time":"2020-04-26T14:20:49.168Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Registering plugin 'bruteForce'...","time":"2020-04-26T14:20:49.169Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Plugin 'bruteForce' registration done.","time":"2020-04-26T14:20:49.172Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Registering plugin 'web'...","time":"2020-04-26T14:20:49.173Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Plugin 'web' registration done.","time":"2020-04-26T14:20:49.233Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Registering plugin 'utils'...","time":"2020-04-26T14:20:49.234Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Plugin 'utils' registration done.","time":"2020-04-26T14:20:49.237Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Registering plugin 'logging'...","time":"2020-04-26T14:20:49.238Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Plugin 'logging' registration done.","time":"2020-04-26T14:20:49.242Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Registering plugin 'api-docs'...","time":"2020-04-26T14:20:49.243Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Plugin 'api-docs' registration done.","time":"2020-04-26T14:20:49.280Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Registering plugin 'DB'...","time":"2020-04-26T14:20:49.281Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":30,"msg":"Connected to Redis server version: 3.2.6","time":"2020-04-26T14:20:49.284Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Plugin 'DB' registration done.","time":"2020-04-26T14:20:49.285Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Registering plugin 'deviceRpc'...","time":"2020-04-26T14:20:49.286Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Plugin 'deviceRpc' registration done.","time":"2020-04-26T14:20:49.293Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Registering plugin 'socketApi'...","time":"2020-04-26T14:20:49.294Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Plugin 'socketApi' registration done.","time":"2020-04-26T14:20:49.301Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Registering plugin 'mail'...","time":"2020-04-26T14:20:49.302Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Plugin 'mail' registration done.","time":"2020-04-26T14:20:49.303Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Registering plugin 'statistics'...","time":"2020-04-26T14:20:49.305Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Plugin 'statistics' registration done.","time":"2020-04-26T14:20:49.306Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Registering plugin 'serverControl'...","time":"2020-04-26T14:20:49.307Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Plugin 'serverControl' registration done.","time":"2020-04-26T14:20:49.309Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Registering plugin 'crm'...","time":"2020-04-26T14:20:49.310Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Plugin 'crm' registration done.","time":"2020-04-26T14:20:49.312Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Registering plugin 'user'...","time":"2020-04-26T14:20:49.314Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Plugin 'user' registration done.","time":"2020-04-26T14:20:49.319Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Registering plugin 'firmwareDal'...","time":"2020-04-26T14:20:49.321Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Plugin 'firmwareDal' registration done.","time":"2020-04-26T14:20:49.356Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Registering plugin 'eventLog'...","time":"2020-04-26T14:20:49.357Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Plugin 'eventLog' registration done.","time":"2020-04-26T14:20:49.361Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":20,"msg":"Registering plugin 'nginx'...","time":"2020-04-26T14:20:49.363Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":30,"msg":"Updating SSL certificate on Nginx for hostname 192.168.10.7","time":"2020-04-26T14:20:49.367Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":30,"msg":"SSL cert for '192.168.10.7' updated successfully","time":"2020-04-26T14:20:49.636Z","v":0}
{"name":"UNMS","hostname":"096eefc5d7c4","pid":3037,"level":60,"err":{"message":"Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379","name":"Error","stack":"Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)","code":"ECONNREFUSED"},"msg":"Redis connection failed, terminating...","time":"2020-04-26T14:20:49.664Z","v":0}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! unms-server@1.1.7 start: `node --max_old_space_size=2048 index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the unms-server@1.1.7 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/app/.npm/_logs/2020-04-26T14_20_49_740Z-debug.log
Running docker-entrypoint npm start
Version: 1.1.7+713785de8.2020-04-22T14:24:35+02:00
Waiting for database containers
NOTICE:  extension "timescaledb" does not exist, skipping
DROP EXTENSION
LOADING Redis is loading the dataset in memory
```

**Comment by Nico640** [comment]
Starting over would be one approach, however, I kinda wanna know what happened as I can't reproduce it ;-). If you don't want to poke around a bit more, you can just start over.

However it seems like redis is not starting. Try opening a shell on the container:
`sudo docker exec -it unms /bin/bash`
and then start redis manually:
`s6-setuidgid abc redis-server --appendonly yes --dir /config/redis/`
Check and paste the output.

**Comment by Danabw** [comment]
OK, all in!  ;-) 
I'm leaving on a 28 mile bike ride w/my son this AM, but I'll do the check above and then when I get back I'll check for follow up.

**Comment by Danabw** [comment]
K - here's what happened:

`pi@raspberrypi4:~ $ sudo docker exec -it unms /bin/bash
root@096eefc5d7c4:/home/app/unms# s6-setuidgid abc redis-server --appendonly yes --dir /config/redis/

20514:M 27 Apr 14:30:58.100 # Creating Server TCP listening socket *:6379: bind: Address already in use
root@096eefc5d7c4:/home/app/unms#
`

**Comment by Nico640** [comment]
Hmm, my guess is that redis keeps restarting. Try shutting down the service first:
```
sudo docker exec -it unms /bin/bash
s6-svc -wd -d /var/run/s6/services/redis/
killall redis-server
s6-setuidgid abc redis-server --appendonly yes --dir /config/redis/
```
if redis starts and doesn't crash right away, try to keep it running for a few minutes to make sure it doesn't crash.

**Comment by Danabw** [comment]
OK, back from the ride (conqured the mountain!!) and ran the new set of commands on the pi: 

`pi@raspberrypi4:~ $ sudo docker exec -it unms /bin/bash
root@096eefc5d7c4:/home/app/unms# s6-svc -wd -d /var/run/s6/services/redis/
root@096eefc5d7c4:/home/app/unms# killall redis-server
redis-server: no process found
root@096eefc5d7c4:/home/app/unms# s6-setuidgid abc redis-server --appendonly yes --dir /config/redis/
31784:M 27 Apr 18:50:46.564 # Warning: 32 bit instance detected but no memory limit set. Setting 3 GB maxmemory limit with 'noeviction' policy now.
                _._
           _.-``__ ''-._
      _.-``    `.  `_.  ''-._           Redis 3.2.6 (00000000/0) 32 bit
  .-`` .-```.  ```\/    _.,_ ''-._
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 31784
  `-._    `-._  `-./  _.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |           http://redis.io
  `-._    `-._`-.__.-'_.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |
  `-._    `-._`-.__.-'_.-'    _.-'
      `-._    `-.__.-'    _.-'
          `-._        _.-'
              `-.__.-'

31784:M 27 Apr 18:50:46.568 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
31784:M 27 Apr 18:50:46.568 # Server started, Redis version 3.2.6
31784:M 27 Apr 18:50:46.568 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
31784:M 27 Apr 18:50:47.183 # Bad file format reading the append only file: make a backup of your AOF file, then use ./redis-check-aof --fix <filename>
root@096eefc5d7c4:/home/app/unms#
`

**Comment by Nico640** [comment]
Looks like the redis aof file somehow got corrupted. Try this:
```
sudo docker exec -it unms /bin/bash
redis-check-aof --fix /config/redis/appendonly.aof
```
then try to start redis again:
`s6-setuidgid abc redis-server --appendonly yes --dir /config/redis/`
if it doesnt crash, let it run for a few minutes and check if UNMS comes up.

**Comment by Danabw** [comment]
I think that did it!  :) 

```
pi@raspberrypi4:~ $ sudo docker exec -it unms /bin/bash
root@096eefc5d7c4:/home/app/unms# redis-check-aof --fix /config/redis/appendonly.aof
0x         323a8ef: Expected prefix '
AOF analyzed: size=52670256, ok_up_to=52668655, diff=1601
This will shrink the AOF from 52670256 bytes, with 1601 bytes, to 52668655 bytes
Continue? [y/N]: y
Successfully truncated AOF
root@096eefc5d7c4:/home/app/unms# s6-setuidgid abc redis-server --appendonly yes --dir /config/redis/
14234:M 27 Apr 19:07:07.317 # Warning: 32 bit instance detected but no memory limit set. Setting 3 GB maxmemory limit with 'noeviction' policy now.
                _._
           _.-``__ ''-._
      _.-``    `.  `_.  ''-._           Redis 3.2.6 (00000000/0) 32 bit
  .-`` .-```.  ```\/    _.,_ ''-._
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 14234
  `-._    `-._  `-./  _.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |           http://redis.io
  `-._    `-._`-.__.-'_.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |
  `-._    `-._`-.__.-'_.-'    _.-'
      `-._    `-.__.-'    _.-'
          `-._        _.-'
              `-.__.-'

14234:M 27 Apr 19:07:07.319 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
14234:M 27 Apr 19:07:07.319 # Server started, Redis version 3.2.6
14234:M 27 Apr 19:07:07.319 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
14234:M 27 Apr 19:07:08.270 * DB loaded from append only file: 0.950 seconds
14234:M 27 Apr 19:07:08.270 * The server is now ready to accept connections on port 6379
```

**Comment by Danabw** [comment]
Following up - been several minutes and the redis service is still in "ready to accept" mode so the fix appears to be stable.

**Comment by Nico640** [comment]
That overcommit warning shouldn't be an issue.
If UNMS is also working, you can exit from the container and reboot it (sudo docker restart unms). That should make the redis service start up automatically again.

**Comment by Danabw** [comment]
I ended up closing the putty session to my pi, redis per your commands above, and am able to launch UNMS! Boom!  Thanks very much!  :) 

So is there anything I need to do w/the open putty connection show redis running and waiting for a connection? Or anything I need to do to keep this working? 

And UNMS asked me to upload the key for my credentials vault, and it won't accept the vault key I'm using. I assume my key would work across upgrades, and no big deal if it doesn't, but wondered if this is a normal issue in some cases, or maybe related to the redis corruption issues?

**Comment by Nico640** [comment]
No problem ;-) I'm glad I could help.
The credentials vault should work across updates, in fact, I just tested it and I was able to unlock the vault. It could be related to the redis aof corruption, however, I'm not sure about that.

**Comment by Danabw** [comment]
K, thanks. I'll create a new key. 

I had some power outages recently caused by an extension cord that my son kept unplugging to plug in something he was using, so that may explain the corruption. 

Really appreciate your help, and that you're maintaining this container.

**Comment by nyamka110** [comment]
Hello Nico640,

I have same issues but now 2.4.175 doesn't have redis, how should I approach this issue?
In my case, unms logs are running fine, except when it's starting, it showed some error log below, but not anymore after a few sec.

{"name":"UNMS","hostname":"9908026156a5","pid":1,"level":50,"err":{"message":"getaddrinfo EAI_AGAIN fw-update.ubnt.com","name":"RequestError","stack":"RequestError: getaddrinfo EAI_AGAIN fw-update.ubnt.com\n    at ClientRequest.<anonymous> (/home/app/unms/node_modules/got/dist/source/core/index.js:970:111)\n    at /home/app/unms/node_modules/@opentelemetry/context-async-hooks/build/src/AbstractAsyncHooksContextManager.js:50:55\n    at AsyncLocalStorage.run (node:async_hooks:330:14)\n    at AsyncLocalStorageContextManager.with (/home/app/unms/node_modules/@opentelemetry/context-async-hooks/build/src/AsyncLocalStorageContextManager.js:33:40)\n    at ClientRequest.contextWrapper (/home/app/unms/node_modules/@opentelemetry/context-async-hooks/build/src/AbstractAsyncHooksContextManager.js:50:32)\n    at Object.onceWrapper (node:events:628:26)\n    at ClientRequest.emit (node:events:525:35)\n    at ClientRequest.emit (node:domain:489:12)\n    at ClientRequest.origin.emit (/home/app/unms/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)\n    at TLSSocket.socketErrorListener (node:_http_client:494:9)\n    at TLSSocket.emit (node:events:513:28)\n    at TLSSocket.emit (node:domain:489:12)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)\n    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17)","code":"EAI_AGAIN"},"msg":"Failed to download latest firmware","time":"2025-01-14T12:33:52.518Z","v":0}

But, ucrm docker is keep restarting:

{"message":"Waiting for UNMS (unms:8081).","channel":"unms_ready.sh","datetime":"2025-01-14T12:40:17+00:00","severity":"INFO","level":200}
{"message":"Waiting for UNMS (unms:8081).","channel":"unms_ready.sh","datetime":"2025-01-14T12:40:21+00:00","severity":"INFO","level":200}
{"message":"Waiting for UNMS (unms:8081).","channel":"unms_ready.sh","datetime":"2025-01-14T12:40:24+00:00","severity":"INFO","level":200}
{"message":"Waiting for UNMS (unms:8081).","channel":"unms_ready.sh","datetime":"2025-01-14T12:40:27+00:00","severity":"INFO","level":200}
{"message":"UNMS did not start in time, restarting container.","channel":"web.sh","datetime":"2025-01-14T12:40:27+00:00","severity":"WARNING","level":300}
make: *** [Makefile:22: server_with_migrate] Error 1


Do you see issues like this?
Do you have any suggestions?

Thank you.

**Comment by Nico640** [comment]
The ucrm container will keep restarting if it's unable to communicate with the unms container. The unms log you posted indicates some kind of networking issue, not sure if it's actually related the problem. Are you sure that there isn't something else unusual in the log?

Also, correct me if I'm wrong, but it looks like you are using an official UISP installation. This repository is for an unofficial all-in-one Docker image, so you might be better off contacting Ubiquiti support.

**Comment by nyamka110** [comment]
> The ucrm container will keep restarting if it's unable to communicate with the unms container. The unms log you posted indicates some kind of networking issue, not sure if it's actually related the problem. Are you sure that there isn't something else unusual in the log?
> 
> Also, correct me if I'm wrong, but it looks like you are using an official UISP installation. This repository is for an unofficial all-in-one Docker image, so you might be better off contacting Ubiquiti support.

Hi,

Ah yes, it's official. 
I fixed the issue somehow. I restored unms from the backup and restarting stopped.
Then I could access after rebooting the server.

Maybe upgrading libseccomp helped too. Not sure.

Anyway, thank you for the comment :)
