### ISSUE TITLE
Add support for ARM64

### ISSUE THREAD

**Issue by oliviermichaelis** [Nico640/docker-unms#29]
Hi @Nico640 ! Since I've been running a 64bit OS on my Raspberry Pis I was interested in adding support for the ARM64 architecture to the UNMS docker image.
Only a couple of small changes were necessary to the `docker-s6-debian-node` Dockerfile and some more to the Dockerfile in  `docker-unms`, which you can check out [here](https://github.com/Nico640/docker-unms/compare/master...oliviermichaelis:arm64).
The changes were basically all about downloading the correct binaries for s6-overlay and node, as well as bumping the `LUA_NGINX_VERSION` from `0.10.13` to `0.10.14` which includes arm64 support.

If you're interested in supporting arm64 images I'd be willing to post a proper PR with all necessary changes.

**Comment by Nico640** [comment]
Sure! Feel free to create a PR, I'll appreciate it.
I was planning to rework my CI pipeline anyway, so this would definitely become part of that ;)

**Comment by oliviermichaelis** [comment]
I opened #31 with the necessary changes to the Dockerfile for arm64.
Let me know if I can help testing the changes!

**Comment by Nico640** [comment]
Images for arm64 are up. I've already tested basic functionality of UNMS and UCRM, but haven't connected any devices to it. Should work fine though.

**Comment by oliviermichaelis** [comment]
Nice, thanks a lot! I'll make sure to test it over the next couple of days with an edgerouter-x.

**Comment by oliviermichaelis** [comment]
Works flawlessly for me so far :)
Thanks a lot!

**Comment by oliviermichaelis** [comment]
Sadly, netflow doesn't work for me on arm64. The netflow process seems to die and stop listening on port 2055.
I ran a container on amd64 where netflow worked as expected.
Here is an output of all log lines containing netflow:
```
Starting unms-netflow...
{"name":"netflow","hostname":"unms-0","pid":351,"level":30,"msg":"Listening for netflow packets on port udp://10.43.78.183:2055 (23 ms)","time":"2020-05-14T18:02:12.813Z","v":0}
{"name":"netflow","hostname":"unms-0","pid":351,"level":30,"msg":"Initializing database","time":"2020-05-14T18:02:12.820Z","v":0}
{"name":"netflow","hostname":"unms-0","pid":351,"level":30,"msg":"Database initialized (132 ms)","time":"2020-05-14T18:02:12.952Z","v":0}
{"name":"netflow","hostname":"unms-0","pid":351,"level":30,"msg":"Initializing RabbitMQ","time":"2020-05-14T18:02:12.954Z","v":0}
{"name":"netflow","hostname":"unms-0","pid":351,"level":50,"msg":"Failed to connect to RabbitMQ: connect ECONNREFUSED 127.0.0.1:5672","time":"2020-05-14T18:02:12.989Z","v":0}
{"name":"netflow","hostname":"unms-0","pid":351,"level":30,"msg":"RabbitMQ initialized (30125 ms)","time":"2020-05-14T18:02:43.079Z","v":0}
{"name":"netflow","hostname":"unms-0","pid":351,"level":30,"msg":"Subscribed for managed networks change notifications at queue 'settings.networks.changed'","time":"2020-05-14T18:02:43.109Z","v":0}
{"name":"netflow","hostname":"unms-0","pid":351,"level":30,"msg":"Subscribed for managed networks change notifications at queue 'settings.blacklist.changed'","time":"2020-05-14T18:02:43.163Z","v":0}
{"name":"netflow","hostname":"unms-0","pid":351,"level":30,"msg":"Subscribed for site IP addresses change notifications at queue 'site.ips.changed'","time":"2020-05-14T18:02:43.177Z","v":0}
{"name":"netflow","hostname":"unms-0","pid":351,"level":30,"msg":"Subscribed for device authorizations at queue 'device.*.authorized'","time":"2020-05-14T18:02:43.192Z","v":0}
{"name":"netflow","hostname":"unms-0","pid":351,"level":30,"msg":"Subscribed for device authorizations at queue 'device.*.settings.changed'","time":"2020-05-14T18:02:43.207Z","v":0}
{"name":"netflow","hostname":"unms-0","pid":351,"level":30,"msg":"Subscribed for settings change notifications at queue 'settings.changed'","time":"2020-05-14T18:02:43.269Z","v":0}
{"name":"netflow","hostname":"unms-0","pid":351,"level":30,"msg":"Loaded list of managed networks from database (35 ms) [ '192.168.1.0/24' ]","time":"2020-05-14T18:02:43.306Z","v":0}
{"name":"netflow","hostname":"unms-0","pid":351,"level":30,"msg":"Loaded blacklist from database (8 ms) []","time":"2020-05-14T18:02:43.319Z","v":0}
{"name":"netflow","hostname":"unms-0","pid":351,"level":30,"msg":"Determined UNMS IP address '192.168.1.241' (89 ms)","time":"2020-05-14T18:02:43.517Z","v":0}
{"name":"UNMS","hostname":"unms-0","pid":1781,"level":20,"msg":"Registering plugin 'netflow'...","time":"2020-05-14T18:03:08.095Z","v":0}
{"name":"UNMS","hostname":"unms-0","pid":1781,"level":20,"msg":"Plugin 'netflow' registration done.","time":"2020-05-14T18:03:08.096Z","v":0}
```

Any ideas on where I should further investigate?

**Comment by Nico640** [comment]
Try starting rabbitmq manually by executing `rabbitmq-server` .
If it's already running, disable the service with `s6-svc -wd -d /var/run/s6/services/rabbitmq/` , shut rabbitmq down `rabbitmqctl stop` and then try to start it again and check for any errors.

**Comment by oliviermichaelis** [comment]
Thanks for the pointers!
Somehow `UNMS_NETFLOW_PORT` is set to `udp://10.43.78.183:2055` instead of `2055`. In my case `10.43.78.183` is the IP of my cluster internal service from which the container receives the netflow traffic.
