### ISSUE TITLE
Log Rotation

### ISSUE THREAD

**Issue by patricegautier** [Nico640/docker-unms#3]
The log file at /srv-internal/data/unms/config/unms/logs/unms.log filled its partition today at 12G and caused the apps to stop functioning.

This is the same issue I believe was described in https://github.com/oznu/docker-unms/issues/48

I see this in my running container:

root@ckv26000:/srv-internal/data/unms# docker exec 305b79531701 cat /etc/logrotate.d/unms
/config/unms/logs/*.log { 
  size 10M
  copytruncate
  missingok
  rotate 7
  compress
  delaycompress
}

But it doesn't seem to have any effect.

**Comment by Nico640** [comment]
I was able to reproduce the issue, however, this only seems to happen on armhf.
It could be that travis's hosts have an umask of 0002, which will cause a file permission of 664.
I will add an manual chmod 644 in the dockerfile.

As already described in the old issue, executing "chmod 644 /etc/logrotate.d/unms" inside the container should fix this.

**Comment by Nico640** [comment]
No problem :)

Should be fixed in the latest build

**Comment by Trunkzeh** [comment]
@Nico640 Was this fix implemented? My unms.log had reached over 11GB the other day. I've deleted it; restarted unms and it re-created a fresh unms.log file; this morning its over 60MB which isnt a big deal however it doesnt appear logrotate is functioning correctly - the logrotate file stipulates the log file to be no bigger than 10MB. Same issue with ucrm.log as well.

**Comment by Nico640** [comment]
Yes it was. The fix just sets the file permission of /etc/logrotate.d/unms and ucrm to 644.
As far as I can see, my logrotate on x86 is working fine.

The cron job for logrotate should run daily, so the files can get bigger than 10MB until logrotate executes.
Try executing "/usr/sbin/logrotate -v /etc/logrotate.conf" on the container and check the output / the log files and see if they get rotated.

**Comment by Trunkzeh** [comment]
@Nico640 Found the problem:

```
rotating pattern: /config/unms/logs/*.log  10485760 bytes (7 rotations)
empty log files are rotated, old logs are removed
considering log /config/unms/logs/ucrm.log
error: skipping "/config/unms/logs/ucrm.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
considering log /config/unms/logs/unms.log
error: skipping "/config/unms/logs/unms.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
```

**Comment by Nico640** [comment]
@Trunkzeh I'm glad you got it fixed! I wonder what happened that it didn't work anymore.
