### ISSUE TITLE
Reduction of writes to drive

### ISSUE THREAD

**Issue by mf808** [Nico640/docker-unms#30]
I have moved to running my docker containers on a ssd due to noise and speed constraints.
One big drawback is, that SSDs have a given number of writes. Once this amount is reached waranty expires and the chance that the drive will go bad are increased. 

UNMS is a container that writes a constant stream of data. In my case I can see a constant write stream of 0,5 MB/s, which does not seem much at a first glance, but if it is calculated x3600x24x356  for a year this equates to upto 15TB yearly. Add several other containers to the mix and the warranty is over.

Is there a way to reduce the amount of disk writes for unms? (reduce logging, etc ) 
Would it be possible to expose a variable to enable the "low writes mode"?

Thanks and regards
Marcus

PS: Thanks for providing this awesome image :)

**Comment by Nico640** [comment]
0,5 MB/s is a lot. I'm not seeing such write speeds. How many devices do you have connected to UNMS? Do you use UCRM? Also, can you track what it's actually writing by checking if the file size of the logs also increase at such speeds? (/config/unms/logs/unms.log / ucrm.log) Another file you could check is the appendonly file (/config/redis/appendonly.aof)
What are you using to check the write speed of the container?

**Comment by Nico640** [comment]
Closed due to inactivity.
