### ISSUE TITLE
Credentials Vault Unlock via Kubernetes Secret

### ISSUE THREAD

**Issue by iamacarpet** [Nico640/docker-unms#33]
Hello guys,

Any idea if an automatic unlock of credentials vault when the container is restarted using a Kubernetes secret (file on disk or environment variable) is possible?

**Comment by Nico640** [comment]
As far as I know, UNMS can't read the vault key from a file or environment variable. But you could try to create a script that unlocks the vault with the UNMS API. Not sure how secure that would be though.
API Docs are available at (your UNMS server)/api-docs

**Comment by oliviermichaelis** [comment]
Just as an idea, you could add a job similar to this one:
https://github.com/influxdata/helm-charts/blob/master/charts/influxdb/templates/post-install-set-auth.yaml
In this case it's creating a user, in your case you could unlock the vault with curl :)

**Comment by Nico640** [comment]
Closed due to inactivity.
