### ISSUE TITLE
1.2.4 Never Starts Up

### ISSUE THREAD

**Issue by NEITG** [Nico640/docker-unms#37]
Pi4 Docker (all latest updates)
Did the same as usual to upgrade - removal of the service, container etc (retaining config dir) and then run:
```
docker service create --name=unms \
--publish=80:80/tcp \
--publish=443:443/tcp \
--publish 2055:2055/udp \
--restart-condition on-failure \
--env TZ=Europe/London \
--mount=type=bind,src=/home/pi/unms,dst=/config \
nico640/docker-unms:armhf
```
Now UNMS never gets beyond "UNMS is starting... This should not take more than a minute." And after 30 mins the splash changes to "Oops! Something went wrong".

Anything I might be missing?

**Comment by Nico640** [comment]
Take a look at both your unms log (/home/pi/unms/unms/logs/unms.log) and your container log (docker logs unms) and check if there's any obvious error or repeating pattern. Please post the last few lines of these logs.

**Comment by NEITG** [comment]
Interesting, docker logs is repeating over and over and over:

`23123:M 04 Jul 19:43:43.663 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
23123:M 04 Jul 19:43:43.663 # Server started, Redis version 3.2.6
23123:M 04 Jul 19:43:43.664 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
{"message":"Creating database extensions.","channel":"database_create_extensions.sh","datetime":"2020-07-04T19:43:43+01:00","severity":"INFO","level":200}
{"message":"Extension \"citext\" exists.","channel":"database_create_extensions.sh","datetime":"2020-07-04T19:43:44+01:00","severity":"INFO","level":200}
{"message":"Extension \"unaccent\" exists.","channel":"database_create_extensions.sh","datetime":"2020-07-04T19:43:44+01:00","severity":"INFO","level":200}
23123:M 04 Jul 19:43:44.677 # Bad file format reading the append only file: make a backup of your AOF file, then use ./redis-check-aof --fix <filename>
Starting redis...
23181:M 04 Jul 19:43:44.694 # Warning: 32 bit instance detected but no memory limit set. Setting 3 GB maxmemory limit with 'noeviction' policy now.`

Otherwise UNMS.log seems normal, mentions running migrations, setting db schema and starting the app:

`> unms-server@1.2.4 start /home/app/unms
> node --max_old_space_size=2048 index.js

{"name":"UNMS","hostname":"d415c1cac295","pid":7707,"level":30,"msg":"Master 7707 is running","time":"2020-07-05T16:45:47.976Z","v":0}
{"name":"UNMS","hostname":"d415c1cac295","pid":7707,"level":30,"msg":"Connected to SiriDB server version: 2.0.34","time":"2020-07-05T16:45:50.731Z","v":0}
{"name":"UNMS","hostname":"d415c1cac295","pid":7707,"level":30,"msg":"Connected to PostgreSQL server version: PostgreSQL 9.6.17 on armv7l-unknown-linux-gnueabihf, $
{"name":"UNMS","hostname":"d415c1cac295","pid":7707,"level":30,"msg":"Registering plugins","time":"2020-07-05T16:45:53.356Z","v":0}`

**Comment by NEITG** [comment]
Bit more useful maybe from docker logs:
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! unms-server@1.2.4 start: `node --max_old_space_size=2048 index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the unms-server@1.2.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/app/.npm/_logs/2020-07-05T16_59_49_370Z-debug.log
FATAL:  role "root" does not exist
/var/run/postgresql:5432 - accepting connections
2020/07/05 17:59:49 [error] 5042#5042: *201 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.0.2, server: , request: "GET // HTTP/1.1", upstream: "http://127.0.0.1:8082//", host: "(ipaddress)"
```

and

`2020/07/05 18:02:15 [error] 5042#5042: *166 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.0.2, server: , request: "GET /nms/api/v2.1/nms/heartbeat HTTP/1.1", upstream: "http://127.0.0.1:8081/nms/api/v2.1/nms/heartbeat", host: "(ipaddress)", referrer: "https://(ipaddress)/nms/dashboard"`

**Comment by Nico640** [comment]
Your redis appendonly file is corrupted. This often happens after a sudden power loss or non-graceful shutdown of the device (Raspberry Pi in this case). Not sure if that's what happened here as it happened after an upgrade.
You can probably fix this issue by opening a bash in the container and executing the redis check aof command.

```
docker exec -it unms /bin/bash
redis-check-aof --fix /config/redis/appendonly.aof
```

**Comment by NEITG** [comment]
That fixed it, ran the check aof rm'd the container and service and redeployed. All up and running.

Interesting we did have a power outage recently but we're on UPS and I issued a shutdown to the pi. Maybe it never completed the process before the UPS drained for some reason.

Thank you for the assist! Will close the issue.
