### ISSUE TITLE
UNMS is starting ... but id does not start

### ISSUE THREAD

**Issue by Roberto6969** [Nico640/docker-unms#40]
Hello!

After long period of regular operation UNMS doesn't start. I have recreated container but it seems it is not problem in container. Container normally starts and is operational. Page of UNMS show rocket till the rocket goes away and message says the UNMS couldn't start: "Oops! Something went wrong."
**unms.log** has following errors:
{"name":"UNMS","hostname":"7d0b24011e93","pid":1934,"level":30,"msg":"SiriDB database 'unms' does not exists. Creating...","time":"2020-10-11T18:25:36.037Z","v":0}
{ SiriDbError: database directory already exists: /config/siridb/unms/
    at SiriDbConnection.resolveRequest (/home/app/unms/lib/siridb/connection.js:155:17)
    at SiriDbConnection.handleData (/home/app/unms/lib/siridb/connection.js:95:14)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17) tp: 96, name: 'SiriDbError' } 'Unexpected error in master process'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! unms-server@1.2.7 start: `node --max_old_space_size=2048 index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the unms-server@1.2.7 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/app/.npm/_logs/2020-10-11T18_25_36_090Z-debug.log
Running docker-entrypoint npm start
Sentry release:
Version: 1.2.7+258cbb8a49.2020-09-18T14:42:15+02:00

Just in case, **ucrm.log** seems OK except this:

{"message":"Waiting for UNMS (127.0.0.1:8081).","channel":"unms_ready.sh","datetime":"2020-10-07T07:00:15+02:00","severity":"INFO","level":200}
{"message":"UNMS did not start in time, restarting container.","channel":"web.sh","datetime":"2020-10-07T07:00:15+02:00","severity":"WARNING","level":300}
Makefile:12: recipe for target 'server_with_migrate' failed
make: *** [server_with_migrate] Error 1
/usr/src/ucrm/scripts/init_log.sh
/usr/src/ucrm/scripts/dirs.sh
{"message":"Creating directories.","channel":"dirs.sh","datetime":"2020-10-07T07:00:15+02:00","severity":"INFO","level":200}
{"message":"Done creating directories.","channel":"dirs.sh","datetime":"2020-10-07T07:00:16+02:00","severity":"INFO","level":200}

There was no changes in configuration, no updates - just normal operation without any changes. As long as I know, UNMS version is 1.2.6 or 1.2.7. How can I approach solving this situation? Thank You!

**Comment by Nico640** [comment]
There seems to be an issue with the siridb database. Try to backup and delete the /config/siridb/unms/ directory.

**Comment by Roberto6969** [comment]
Indeed - my UNMS is back. The path to the unms directory is slightly different but /siris/unms is the same. Thank You!
