### ISSUE TITLE
UNMS 1.3.1 avalible

### ISSUE THREAD

**Issue by Snotmann** [Nico640/docker-unms#43]
Hey Nico640,

could you be so kind and build a UNMS with the new version 1.3.1 witch came out today ?

Regards,
Snot

**Comment by Nico640** [comment]
I currently do not release images using beta versions of UNMS, as the inner workings of them change rather rapidly.
However, the testing image (nico640/docker-unms:testing) currently includes UNMS 1.3.1, but I do not recommend using the testing tag for anything else than testing, so make sure you backup your UNMS data if you want to try it out.

**Comment by Nico640** [comment]
I'm closing this as UNMS 1.3 is out of beta now and the UNMS 1.3.7 container is available :-)
