### ISSUE TITLE
Reverse proxy setup not working

### ISSUE THREAD

**Issue by slash1387** [Nico640/docker-unms#47]
Hello
Why is it not possible to run behind a reverse proxy? I get too many redirects to HTTPS when hitting my root url...
Docker expose 10081:80 and 12055:2055, reverse proxy from root url (standard 443) -> localhost:10081.
How do I need to set the env vars for this setup?

edit: It seems like that it's not possible to expose only http right? Or do you know how to set it up via env vars?

Cheers
Alex

**Comment by gnammyx** [comment]
Hello, my unms instance works better behind a Traefik reverse proxy, what's your setup

**Comment by Nico640** [comment]
I also have an UNMS instance running behind a nginx reverse proxy redirecting to the https port of UNMS. The http port is only used for redirecting (and Let's Encrypt) as far as I know. Is there any particular reason that you want to use the http port? I don't think you can set it up via env vars, you would probably need to remove the https configuration of the nginx webserver running inside the container.

**Comment by slash1387** [comment]
Yeah i tried to do ssl termination with synology nas and manage certificate on synology side in the reverse proxy settings :)
