### ISSUE TITLE
Failed to create endpoint

### ISSUE THREAD

**Issue by codefreak558** [Nico640/docker-unms#55]
I'm not sure if I'm doing something wrong I reinstall docker and it didn't change the error
The current error:
`23a8d28c9d6443f6e87e6e6fe2515773e7f7751724e70366bfaf1c21d9b40ad3
docker: Error response from daemon: failed to create endpoint unms3 on network bridge: failed to add the host (vethbe530b8) <=> sandbox (vethe716f2d) pair interfaces: operation not supported.`

Command run:
`sudo docker run -d --name unms3 -p 80:80 -p 443:443 -p 2055:2055/udp -v /var/lib/docker-config/unms:/config nico640/docker
-unms:armhf`

It is running on a raspberry pi 4 with 4gb of ram

**Comment by Nico640** [comment]
What OS / distro are you running on the Raspberry Pi? This sounds like an issue with the docker networking, possibly due to the kernel missing functionality that docker needs.
Are you trying to use the container for the first time or did it already work before?

**Comment by codefreak558** [comment]
I am running the script for the first time and I am running raspberry os lite

**Comment by Nico640** [comment]
I assume you already tried restarting the Raspberry Pi? My guess would be that a kernel module, specifically the `veth` module, is not loaded, which is often fixed by a restart. If not, check if the module is loaded:

```
modinfo veth
ip link add vetha type veth peer name vethb
```
