### ISSUE TITLE
Update to 1.4.2?

### ISSUE THREAD

**Issue by clarkycal** [Nico640/docker-unms#56]
Hi Nico,

The USIP/UNMS team released version 1.4.2: https://community.ui.com/releases/UISP-1-4-2/9a1f73df-ac97-4ad0-8ad9-763049e38cc7

Can we expect the docker image to be updated?

**Comment by clarkycal** [comment]
Ah, i see you're working on it on the "testing" branch.

I will await your green light

**Comment by Nico640** [comment]
https://github.com/Nico640/docker-unms/releases/tag/1.4.2 🎉
