### ISSUE TITLE
s6-applyuidgid: fatal: unable to exec openresty: No such file or directory

### ISSUE THREAD

**Issue by shker-tt** [Nico640/docker-unms#57]
https://github.com/Nico640/docker-unms/blob/042f93762c8b413191a13bd6ffbb04e1dd1226cd/root/etc/services.d/nginx/run#L25

`s6-setuidgid root /usr/local/openresty/bin/openresty -g "daemon off;"`

**Comment by Nico640** [comment]
Are you using Portainer by any chance? This might be the same issue as described [here](https://github.com/Nico640/docker-unms/issues/48#issuecomment-792264832). Try clearing the environment varibles set for the container.

 I'm going to circumvent this issue in the next version by not using the PATH environment variable set by the Dockerfile anymore.

**Comment by shker-tt** [comment]
emm.. synology
