### ISSUE TITLE
100% CPU Load on openSSL at upgrade

### ISSUE THREAD

**Issue by Snotmann** [Nico640/docker-unms#59]
Hey guys,

dont know why but after the update to the new container my cpu runs amok.

top - 11:44:44 up 45 min,  1 user,  load average: 5.60, 4.23, 3.44
Tasks: 182 total,   5 running, 176 sleeping,   0 stopped,   1 zombie
%Cpu(s): 31.4 us,  4.8 sy,  0.0 ni, 31.1 id, 32.7 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :   1872.2 total,     88.9 free,    618.5 used,   1164.8 buff/cache
MiB Swap:    100.0 total,      2.1 free,     97.9 used.   1038.7 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
 4618 911       20   0    3228   2604   2280 R 100.0   0.1   0:21.82 openssl

... tried delete the folders and container but after setting up the same is happen.

Regards,
Snot

**Comment by Snotmann** [comment]
This process hangs:
0:49 openssl req -nodes -x509 -newkey rsa:4096 -subj /CN=localhost -keyout /cert/localhost.key -out /cert/localhost.crt -days 825 -batch -config /openssl.cnf

**Comment by Snotmann** [comment]
OK fixed problem simply use the old version :
docker pull nico640/docker-unms:1.3.11

Thanks alot

**Comment by Nico640** [comment]
Thats interesting... Did you check if the docker logs for the container were showing something interesting? Also, can you share some more details, like what device / architecture and OS are you running on? What is your docker and kernel version? How did you start the container, did you use a command like in the README, or do you use some kind of management interface? 
Anything else that might be noteworthy? I'll try to reproduce this so that I can investigate.

**Comment by Snotmann** [comment]
Hey Nico,

got it tried on a RPI4. Im on it ... the time is 1970 so the openssl cant create the certificate.  Im on Raspberian 
Linux raspberrypi 5.10.63-v7l+ #1496 SMP Wed Dec 1 15:58:56 GMT 2021 armv7l GNU/Linux
I start it like this:
sudo docker run -d --name unms --restart unless-stopped -p 9443:443 -e PUBLIC_HTTPS_PORT=9443 -e PUBLIC_WS_PORT=9443 -v /home/pi/unms/config:/config nico640/docker-unms:latest

Maybe this is the problem:
pi@raspberrypi:/etc $ sudo docker exec -it unms date
Thu Jan  1 00:00:00 UTC 1970

Anything i can do further to investigate ?!

Snot

**Comment by Nico640** [comment]
That sounds a lot like the libseccomp issue that occurs with an older libseccomp version (Debian Buster), 32bit ARM and Alpine Linux 3.13 which causes these time issues inside the container. Check if your libseccomp version is below 2.4.2. If it is, you'll need to update it. You can either update libseccomp manually, add buster-backports to your apt sources and update it that way, or update to Raspberry Pi OS 11 (Debian Bullseye), which has a newer libseccomp version.

This seems to be a pretty good explanation: https://docs.linuxserver.io/faq#libseccomp

**Comment by Snotmann** [comment]
libseccomp2 is already the newest version (2.3.3-4) is the version installed.
sudo apt install libseccomp2 /buster-backports now and got 2.5.1 

Now its hanging at: Application is loading. 1 min remaining...

... i have to debug this a little further.

Thanks for your help @Nico640
