### ISSUE TITLE
netflow

### ISSUE THREAD

**Issue by Yokaze3** [Nico640/docker-unms#60]
Hi.
I installed the image 1.4.2 like i did 1.39 before and everything works fine except one thing. Netflow isnt working for no reason. I have placed the ports correctly like i had them in 1.3.9 but still i cant make it enable although i have 2 gateway installed of ubiquiti edgerouter. Any ideas?

**Comment by Nico640** [comment]
You're right, netflow doesn't appear to start, it's stuck on `Initializing database`. I also noticed that the official netflow docker image actually still uses Node.js 12.18.4, which is most likely the issue. I'm preparing a fix on the testing branch / tag, please test it after it's done building and check if it works.

**Comment by Yokaze3** [comment]
Sorry for being noob....but where i see test branch? i am new here

**Comment by Yokaze3** [comment]
Ok i think i found it in actions. After you finished it plz describe how i will install the update. Thank you very much in advance.

**Comment by Nico640** [comment]
It was automatically pushed to docker hub. Instead of using the `latest` or `1.4.2` tag, you can use the `testing` tag when starting / creating the container

For example: 

`docker run -d --name unms -p 80:80 -p 443:443 -p 2055:2055/udp -v </path/to/config>:/config nico640/docker-unms:testing`

**Comment by Nico640** [comment]
Should be fixed since image version 1.4.3
