### ISSUE TITLE
cant start unms after update

### ISSUE THREAD

**Issue by tobyknobi** [Nico640/docker-unms#63]
Ive tryed everthing. but even on a freshly installed pi it wont come up
Creating network "unms_default" with the default driver
Creating unms_unms_1 ... error

ERROR: for unms_unms_1  Cannot start service unms: cgroups: cgroup mountpoint does not exist: unknown

ERROR: for unms  Cannot start service unms: cgroups: cgroup mountpoint does not exist: unknown
ERROR: Encountered errors while bringing up the project.

i am now on bullseye and the newest libseccomp2
| 
unms_1  |               Starting broker...
unms_1  | 2022-02-09 17:53:19.294 CET [882] FATAL:  the database system is starting up
unms_1  | /tmp:5432 - rejecting connections

**Comment by Nico640** [comment]
I would guess that docker isn't installed correctly. How did you install docker on the Pi? Did you use the instructions from the official docker website or did you simply install docker using apt? Also, what is your docker version? (`docker -v`)

The last three lines of log look fine to me, this is how it should look like while starting up. Is that the only thing being logged? If not, please post a complete log of the startup.

**Comment by tobyknobi** [comment]
thanks for responding so fast,

i just fixed it.
i installed it first with docker compose.
but went to your install . so first i installed docker the original way
then started it with docker run etc.
no it runs fine.
just docker start unms and it come up.
also went to a 64 bit os pi.

Greetz i will update my post on git
thanks gain

Op wo 9 feb. 2022 20:50 schreef Nico640 ***@***.***>:
