### ISSUE TITLE
v1.4.3 update

### ISSUE THREAD

**Issue by fate8383** [Nico640/docker-unms#64]
Hello, I am new to whole docker environment, I see that you do not have the new version 1.4.3, i will wait for it. Just want to know how do I update? complete new image and new compose or just update the yml with new tag and run it up again? Thanks

**Comment by Nico640** [comment]
You just need to update the yml. If you use the version tags, e.g. `1.4.2`, you can simply set the new tag and run `docker-compose up -d`. If you use the `latest` tag, you might need to pull the new image first (`docker-compose pull`)

**Comment by fate8383** [comment]
thanks it worked.
