### ISSUE TITLE
Problem after Update to Raspberian 11

### ISSUE THREAD

**Issue by Snotmann** [Nico640/docker-unms#74]
I dont know why but after i updated to raspberian 11 and updated my UNMS installation i got this errors and no idea how to fix that ?!

make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022-09-04 12:05:07.027 UTC [6769] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
Checking CRM database schema version.
2022-09-04 12:05:07.517 UTC [6773] ERROR:  relation "crm_db_version_view" does not exist at character 19
2022-09-04 12:05:07.517 UTC [6773] STATEMENT:  SELECT value FROM crm_db_version_view
relation "crm_db_version_view" does not exist
Retrying in 10s
2022-09-04 12:05:08.030 UTC [6779] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022-09-04 12:05:09.033 UTC [6786] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022-09-04 12:05:10.037 UTC [6793] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022-09-04 12:05:11.040 UTC [6800] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022-09-04 12:05:12.043 UTC [6807] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022-09-04 12:05:13.047 UTC [6814] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022-09-04 12:05:14.050 UTC [6826] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022-09-04 12:05:15.054 UTC [6833] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022-09-04 12:05:16.058 UTC [6840] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022-09-04 12:05:17.061 UTC [6847] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
Checking CRM database schema version.
2022-09-04 12:05:17.536 UTC [6851] ERROR:  relation "crm_db_version_view" does not exist at character 19
2022-09-04 12:05:17.536 UTC [6851] STATEMENT:  SELECT value FROM crm_db_version_view
relation "crm_db_version_view" does not exist
Retrying in 10s
2022-09-04 12:05:18.064 UTC [6857] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022-09-04 12:05:19.067 UTC [6864] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022-09-04 12:05:20.071 UTC [6871] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022/09/04 12:05:20 [error] 799#799: *427 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.2.1, server: , request: "GET // HTTP/1.1", upstream: "http://127.0.0.1:8082//", host: "192.168.2.71"
2022-09-04 12:05:21.074 UTC [6878] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022/09/04 12:05:21 [error] 799#799: *429 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.2.70, server: , request: "GET // HTTP/1.1", upstream: "http://127.0.0.1:8082//", host: "192.168.2.71"
2022-09-04 12:05:22.077 UTC [6885] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022/09/04 12:05:22 [error] 799#799: *431 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.1.2, server: , request: "GET // HTTP/1.1", upstream: "http://127.0.0.1:8082//", host: "192.168.2.71"
2022-09-04 12:05:23.080 UTC [6892] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022-09-04 12:05:24.083 UTC [6899] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022/09/04 12:05:24 [error] 799#799: *433 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.1.3, server: , request: "GET // HTTP/1.1", upstream: "http://127.0.0.1:8082//", host: "192.168.2.71"
2022-09-04 12:05:25.086 UTC [6907] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022-09-04 12:05:26.089 UTC [6914] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022-09-04 12:05:27.095 UTC [6921] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
Checking CRM database schema version.
2022-09-04 12:05:27.561 UTC [6927] ERROR:  relation "crm_db_version_view" does not exist at character 19
2022-09-04 12:05:27.561 UTC [6927] STATEMENT:  SELECT value FROM crm_db_version_view
relation "crm_db_version_view" does not exist
Retrying in 10s
2022-09-04 12:05:28.095 UTC [6932] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022-09-04 12:05:29.101 UTC [6941] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022-09-04 12:05:30.100 UTC [6948] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022-09-04 12:05:31.103 UTC [6955] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022-09-04 12:05:32.107 UTC [6962] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022-09-04 12:05:33.109 UTC [6969] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022-09-04 12:05:34.114 UTC [6977] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022-09-04 12:05:35.122 UTC [6984] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022-09-04 12:05:36.125 UTC [6991] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022-09-04 12:05:37.130 UTC [6998] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
Checking CRM database schema version.
2022-09-04 12:05:37.579 UTC [7004] ERROR:  relation "crm_db_version_view" does not exist at character 19
2022-09-04 12:05:37.579 UTC [7004] STATEMENT:  SELECT value FROM crm_db_version_view
relation "crm_db_version_view" does not exist
Retrying in 10s
2022-09-04 12:05:38.132 UTC [7008] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022-09-04 12:05:39.137 UTC [7015] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022-09-04 12:05:40.139 UTC [7022] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022/09/04 12:05:40 [error] 799#799: *435 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.2.1, server: , request: "GET // HTTP/1.1", upstream: "http://127.0.0.1:8082//", host: "192.168.2.71"
2022-09-04 12:05:41.149 UTC [7029] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022/09/04 12:05:41 [error] 801#801: *437 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.2.70, server: , request: "GET // HTTP/1.1", upstream: "http://127.0.0.1:8082//", host: "192.168.2.71"
2022-09-04 12:05:42.160 UTC [7036] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022/09/04 12:05:42 [error] 801#801: *439 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.1.2, server: , request: "GET // HTTP/1.1", upstream: "http://127.0.0.1:8082//", host: "192.168.2.71"
2022-09-04 12:05:43.156 UTC [7043] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022/09/04 12:05:43 [error] 801#801: *441 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.1.3, server: , request: "GET // HTTP/1.1", upstream: "http://127.0.0.1:8082//", host: "192.168.2.71"
2022-09-04 12:05:44.160 UTC [7051] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127

**Comment by Nico640** [comment]
Can you try to grab the logs at the beginning so that it shows the container startup? Also, please post your container start command and / or the environment variables set for the container (if any). Looks like a permission issue but it's hard to tell the cause without seeing the startup logs as these contain the user / group information used for the unms user.

**Comment by Snotmann** [comment]
Ney Nico,

i started it with this:
sudo docker run -d --name unms --restart unless-stopped -p 9443:443 -e PUBLIC_HTTPS_PORT=9443 -e PUBLIC_WS_PORT=9443 -v /home/pi/unms nico640/docker-unms:latest

And this is what the logs say:
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun netflow (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
services-up: info: copying legacy longrun postgres (no readiness notification)
services-up: info: copying legacy longrun rabbitmq (no readiness notification)
services-up: info: copying legacy longrun siridb (no readiness notification)
services-up: info: copying legacy longrun ucrm (no readiness notification)
services-up: info: copying legacy longrun unms (no readiness notification)
s6-rc: info: service legacy-services successfully started
Starting siridb-server...
Starting nginx...
Waiting for rabbitmq to start...
Starting postgres...
Starting rabbitmq-server...
/run/postgresql:5432 - no response
Waiting for postgres to come up...
Running entrypoint.sh
/run/postgresql:5432 - no response
Waiting for postgres to come up...
Creating nginx configuration
Enabling UNMS https and wss connections on port 443
2022-09-05 06:18:16.537 UTC [164] LOG:  starting PostgreSQL 13.8 on armv7-alpine-linux-musleabihf, compiled by gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, 32-bit
2022-09-05 06:18:16.539 UTC [164] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2022-09-05 06:18:16.539 UTC [164] LOG:  could not bind IPv6 address "::1": Address not available
2022-09-05 06:18:16.539 UTC [164] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
2022-09-05 06:18:16.755 UTC [164] LOG:  listening on Unix socket "/run/postgresql/.s.PGSQL.5432"
Will use existing SSL certificate
2022-09-05 06:18:17.062 UTC [412] LOG:  database system was shut down at 2022-09-04 12:19:09 UTC
2022-09-05 06:18:17.086 UTC [164] LOG:  database system is ready to accept connections
Entrypoint finished
Calling exec
Waiting for pid file '/var/lib/rabbitmq/mnesia/rabbit@9dd2274020a0.pid' to appear
pid is 134
Waiting for erlang distribution on node 'rabbit@9dd2274020a0' while OS process '134' is running
Error:
process_not_running
2022-09-05 06:18:18.154 UTC [489] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
Starting unms-netflow...
2022-09-05 06:18:19.368 UTC [597] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
2022-09-05 06:18:19.370 UTC [598] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022-09-05 06:18:19.418 UTC [609] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022-09-05 06:18:20.454 UTC [624] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
Running docker-entrypoint /home/app/unms/index.js
Sentry release:
Version: 1.4.7+7ffead8cda.2022-08-07T08:35:11+02:00
Waiting for database containers
{"name":"netflow","hostname":"9dd2274020a0","pid":490,"level":30,"msg":"Listening for netflow packets on port 2055 (11 ms)","time":"2022-09-05T06:18:21.012Z","v":0}
{"name":"netflow","hostname":"9dd2274020a0","pid":490,"level":30,"msg":"Initializing database","time":"2022-09-05T06:18:21.020Z","v":0}
{"name":"netflow","hostname":"9dd2274020a0","pid":490,"level":30,"msg":"Database initialized (79 ms)","time":"2022-09-05T06:18:21.099Z","v":0}
{"name":"netflow","hostname":"9dd2274020a0","pid":490,"level":30,"msg":"Initializing RabbitMQ","time":"2022-09-05T06:18:21.100Z","v":0}
{"name":"netflow","hostname":"9dd2274020a0","pid":490,"level":50,"msg":"Failed to connect to RabbitMQ: connect ECONNREFUSED [127.0.0.1:5672](http://127.0.0.1:5672/)","time":"2022-09-05T06:18:21.127Z","v":0}
2022-09-05 06:18:21.409 UTC [654] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022/09/05 06:18:21 [error] 422#422: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.2.70, server: , request: "GET // HTTP/1.1", upstream: "http://127.0.0.1:8082//", host: "192.168.2.71"
2022/09/05 06:18:21 [error] 422#422: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.2.1, server: , request: "GET // HTTP/1.1", upstream: "http://127.0.0.1:8082//", host: "192.168.2.71"
2022-09-05 06:18:22.418 UTC [663] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022/09/05 06:18:22 [error] 422#422: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.1.2, server: , request: "GET // HTTP/1.1", upstream: "http://127.0.0.1:8082//", host: "192.168.2.71"

  ##  ##
  ##  ##      RabbitMQ 3.7.14. Copyright (C) 2007-2019 Pivotal Software, Inc.
  ##########  Licensed under the MPL.  See https://www.rabbitmq.com/
  ######  ##
  ##########  Logs: /var/log/rabbitmq/rabbit@9dd2274020a0.log
                    /var/log/rabbitmq/rabbit@9dd2274020a0_upgrade.log

              Starting broker...
2022-09-05 06:18:23.420 UTC [672] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022/09/05 06:18:23 [error] 422#422: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.1.3, server: , request: "GET // HTTP/1.1", upstream: "http://127.0.0.1:8082//", host: "192.168.2.71"
/run/postgresql:5432 - accepting connections
2022-09-05 06:18:24.440 UTC [681] FATAL:  role "root" does not exist
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022-09-05 06:18:25.436 UTC [690] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022-09-05 06:18:26.439 UTC [707] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
 completed with 0 plugins.
Restoring backups and/or running migrations
2022-09-05 06:18:27.442 UTC [733] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
yarn run v1.22.15
$ yarn backup:apply && yarn migrate && yarn check-crm-db
2022-09-05 06:18:28.446 UTC [752] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
$ node -r ts-node/register/transpile-only ./cli/apply-backup
2022-09-05 06:18:29.452 UTC [770] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022-09-05 06:18:30.487 UTC [777] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022-09-05 06:18:31.490 UTC [784] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022-09-05 06:18:32.485 UTC [791] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022-09-05 06:18:33.502 UTC [798] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022-09-05 06:18:34.533 UTC [805] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022-09-05 06:18:35.492 UTC [812] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127
2022-09-05 06:18:36.506 UTC [821] FATAL:  role "root" does not exist
/run/postgresql:5432 - accepting connections
/usr/src/ucrm/scripts/init_log.sh
make: /usr/src/ucrm/scripts/init_log.sh: Operation not permitted
make: *** [Makefile:25: parameters] Error 127

**Comment by Nico640** [comment]
Hmm, weird, everything seems to be fine besides that `Operation not permitted` error, but I'm still missing the logs of the early stage of the startup, how are you checking / copying the logs? Are you attaching to the container and then copying them? The easiest way to get the full logs is to use `docker logs unms`.

Try to delete the container, pull the image again, create a new container and then get the logs using `docker logs unms` after the error starts repeating in the logs.
Something like this:
```
sudo docker stop unms
sudo docker rm unms
sudo docker pull nico640/docker-unms:latest
sudo docker run -d --name unms --restart unless-stopped -p 9443:443 -e PUBLIC_HTTPS_PORT=9443 -e PUBLIC_WS_PORT=9443 -v /home/pi/unms nico640/docker-unms:latest
sudo docker logs unms
```

<details>
<summary>The beginning of the logs should look similar to this</summary>

> s6-rc: info: service s6rc-oneshot-runner: starting
> s6-rc: info: service s6rc-oneshot-runner successfully started
> s6-rc: info: service fix-attrs: starting
> s6-rc: info: service fix-attrs successfully started
> s6-rc: info: service legacy-cont-init: starting
> cont-init: info: running /etc/cont-init.d/10-set-timezone
> cont-init: info: /etc/cont-init.d/10-set-timezone exited 0
> cont-init: info: running /etc/cont-init.d/20-adduser
> 
> -------------------------------------
> GID/UID
> -------------------------------------
> User uid:    911
> User gid:    911
> -------------------------------------
> 
> cont-init: info: /etc/cont-init.d/20-adduser exited 0
> cont-init: info: running /etc/cont-init.d/30-prepare
> cont-init: info: /etc/cont-init.d/30-prepare exited 0
> cont-init: info: running /etc/cont-init.d/40-permissions
> cont-init: info: /etc/cont-init.d/40-permissions exited 0
> cont-init: info: running /etc/cont-init.d/50-postgres
> The files belonging to this database system will be owned by user "unms".

</details>

Also, if the error still persists after re-creating the container, open a shell inside the container and look at the permissions of `/usr/src/ucrm/scripts/init_log.sh`:

```
sudo docker exec -it unms /bin/bash
ls -l /usr/src/ucrm/scripts/
```
they should look like this: `-rwxrwxr-x 1 unms unms    49 Jan 20  2022 init_log.sh`

**Comment by Snotmann** [comment]
Use 1.4.5-beta and this version is working now !
