### ISSUE TITLE
0.14.4 > 1.0.2

### ISSUE THREAD

**Issue by glc650** [Nico640/docker-unms#8]
I'm getting prompted to update from 0.14.4 to 1.0.2 inside the current stable image.  I don't see any tags for the 1.x builds and if I'm not mistaken, ubnt is now dropping the pre-1.0 builds (so no more unms stable builds w/o crm).  Will you be doing the same for your images or what's your plans for the new stable versions?

Thanks,

->g.

**Comment by Nico640** [comment]
Yes, I will be doing the same.
There isn't really a way around integrating ucrm into the image, as more and more parts of unms depend on ucrm (like unms backups).
I actually already have most parts of unms 1.0.3 running, however, there are still some issues with ucrm plugins, which I am currently working on.

**Comment by glc650** [comment]
ok thanks

**Comment by Nico640** [comment]
Image updated to 1.0.3
