### ISSUE TITLE
UISP never starts. Container restarts

### ISSUE THREAD

**Issue by jakobfriis** [Nico640/docker-unms#88]
Using this compose file 

version: '2'
services:
  unms:
    image: nico640/docker-unms:latest
    restart: always
    restart: unless-stopped
    ports:
      - 8443:443
    environment:
      - PUBLIC_HTTPS_PORT=8443
      - PUBLIC_WS_PORT=8443
      - TZ=Europe/Copenhagen
    volumes:
      - /data/storage/dockervolumes/uisp:/config

The following logs are shown:

{"name":"netflow","hostname":"0965bdafce4d","pid":493,"level":50,"msg":"Failed to determine UNMS IP address: Failed to resolve hostname: b3e03ed9e9d7 (5033 ms)","time":"2023-04-02T18:49:31.512Z","v":0}
{"message":"Waiting for UNMS (127.0.0.1:8081).","channel":"unms_ready.sh","datetime":"2023-04-02T20:49:31+02:00","severity":"INFO","level":200}
{"name":"UNMS","hostname":"0965bdafce4d","pid":1426,"component":"ws","level":30,"msg":"WS server running at ws://:::8082","time":"2023-04-02T18:49:31.840Z","v":0}
{"name":"UNMS","hostname":"0965bdafce4d","pid":1432,"component":"ws","level":30,"msg":"WS server running at ws://:::8082","time":"2023-04-02T18:49:32.003Z","v":0}
{"name":"UNMS","hostname":"0965bdafce4d","pid":1446,"component":"ws","level":30,"msg":"WS server running at ws://:::8082","time":"2023-04-02T18:49:32.005Z","v":0}
{"name":"UNMS","hostname":"0965bdafce4d","pid":1439,"component":"ws","level":30,"msg":"WS server running at ws://:::8082","time":"2023-04-02T18:49:32.160Z","v":0}

{"message":"Waiting for UNMS (127.0.0.1:8081).","channel":"unms_ready.sh","datetime":"2023-04-02T20:51:43+02:00","severity":"INFO","level":200}
{"message":"UNMS did not start in time, restarting container.","channel":"web.sh","datetime":"2023-04-02T20:51:43+02:00","severity":"WARNING","level":300}
make: *** [Makefile:22: server_with_migrate] Error 1
2023-04-02 20:51:43.873 CEST [2963] FATAL:  role "root" does not exist

Any ideas ?

**Comment by Nico640** [comment]
The logs you posted look fine to me, what happens when you open the website at port 8443? Do you get the `Please Wait` page or nothing at all?

**Comment by jakobfriis** [comment]
I restarted the entire server, and after that, the container works fine on port 8443.
I have no idea why - just happy it works now
