### ISSUE TITLE
Update to 2.2.12

### ISSUE THREAD

**Issue by aacebedo** [Nico640/docker-unms#90]
Ubiquiti has updated the UISP to 2.2.12.

Is there an issue to update to it as the container is on 1.7.5?

Regards

**Comment by Nico640** [comment]
Hi,

no, there isn't really an issue, but because it's a rather big update and I haven't had a lot of spare time to work on it lately, it has taken a bit longer. But it's updated on the testing branch now and it will be on master soon :)

**Comment by aacebedo** [comment]
Great news ! 

Thank you for the work on the container, it is very useful.
