### ISSUE TITLE
Connection refused while connecting to upstream, client

### ISSUE THREAD

**Issue by nanordas** [Nico640/docker-unms#93]
Hi, I have installed on a Synology docker, but this errors comes up when starting:

2023/07/18 15:31:59 [error] 499#499: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.17.0.1, server: , request: "GET /nms/api/v2.1/nms/heartbeat HTTP/1.1", upstream: "http://127.0.0.1:8081/nms/api/v2.1/nms/heartbeat", host: "192.168.22.151:9443", referrer: "https://192.168.22.151:9443/nms/"

2023/07/18 15:32:03 [error] 499#499: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.17.0.1, server: , request: "GET /nms/api/v2.1/nms/heartbeat HTTP/1.1", upstream: "http://127.0.0.1:8081/nms/api/v2.1/nms/heartbeat", host: "192.168.22.151:9443", referrer: "https://192.168.22.151:9443/nms/"

2023/07/18 15:32:07 [error] 499#499: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.17.0.1, server: , request: "GET /nms/api/v2.1/nms/heartbeat HTTP/1.1", upstream: "http://127.0.0.1:8081/nms/api/v2.1/nms/heartbeat", host: "192.168.22.151:9443", referrer: "https://192.168.22.151:9443/nms/"

Checking CRM database schema version.

No data returned from the query.

Retrying in 10s

192.168.11.151 is the NAS

These are the commands used at installation:

docker run -d --name=UISP \
  --restart=unless-stopped \
  -e PUBLIC_HTTPS_PORT=9443 \
  -e PUBLIC_WS_PORT=9443 \
  -e HTTPS_PORT=9443 \
  -e HTTP_PORT=9480 \
  -p 9480:9480 \
  -p 9443:9443 \
  -p 2055:2055/udp \
  -e TZ=Europe/Oslo \
  -v /volume1/docker/UISP:/config \
--restart always \
  nico640/docker-unms:latest

Is it because the upstream IP and port are wrong?
upstream: http://127.0.0.1:8081

How to fix this?

Regards Andreas

**Comment by Nico640** [comment]
Hi, the upstream IP and port are correct. The message is coming from the nginx server running inside the container, which is proxying to UISP, which running as a Node.js app. The message is normal on startup and happens when UISP is not fully started yet. What happens when you try to access UISP (https://192.168.11.151:9443)? Do you get the "Please Wait" page? If UISP is not starting up, there has to be a different error in the logs. Check for repeating patterns in the logs or post a full log and I'll try to take a look at it.

**Comment by nanordas** [comment]
Hello and thank you for the reply.

Yes, it is working now. It was just me lacking patience 😉

________________________________
Fra: Nico640 ***@***.***>
Sendt: torsdag 20. juli 2023 23:11
Til: Nico640/docker-unms ***@***.***>
Kopi: Narve Andreas Nordås ***@***.***>; Author ***@***.***>
Emne: Re: [Nico640/docker-unms] Connection refused while connecting to upstream, client (Issue #93)


Hi, the upstream IP and port are correct. The message is coming from the nginx server running inside the container, which is proxying to UISP, which running as a Node.js app. The message is normal on startup and happens when UISP is not fully started yet. What happens when you try to access UISP (https://192.168.11.151:9443)? Do you get the "Please Wait" page? If UISP is not starting up, there has to be a different error in the logs. Check for repeating patterns in the logs or post a full log and I'll try to take a look at it.
